/**
 * Cross-implementation conformance: the TypeScript reference must keep
 * producing the committed corpus, and the Rust crate asserts against the same
 * files (`crates/wh40kdc/tests/conformance.rs`). The corpus is generated by
 * `npm run gen:conformance`; a CI drift guard keeps it current.
 *
 * Three layers are pinned:
 * 1. `normalizeName` against every entry in `normalize.json`.
 * 2. Every roster fixture: each `input.*` file imports to the same
 *    `expected.roster.json`.
 * 3. Every export target: `exportRoster(roster, fmt)` reproduces each
 *    `expected.<fmt>.{txt,json}` golden byte-for-byte.
 */
import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { Dataset } from "../src/data/dataset.js";
import { normalizeName } from "../src/data/normalize.js";
import { exportRoster, type ExportFormat } from "../src/export/index.js";
import { importRoster, tryImportRoster } from "../src/import/import-roster.js";
import type { RosterFormat } from "../src/import/types.js";
import { crunch, type Buff, type EngineContext, type Stage } from "../src/cruncher/index.js";
import type { Phase } from "../src/generated.js";
import { effectToBuffs } from "../src/cruncher/from-dsl.js";
import type { EligibilityInput } from "../src/abilities-resolver/index.js";

const CONFORMANCE = join(dirname(fileURLToPath(import.meta.url)), "../../conformance");
const readJson = (path: string): unknown => JSON.parse(readFileSync(path, "utf8"));
const readText = (path: string): string => readFileSync(path, "utf8");

interface InputDescriptor {
  filename: string;
  /** When `.json`, parse before importing; when `.txt`, pass the raw string. */
  parseAsJson: boolean;
}

const TEXT_EXPORTS: { format: ExportFormat; filename: string }[] = [
  { format: "newrecruit-wtc-compact", filename: "expected.newrecruit-wtc-compact.txt" },
  { format: "newrecruit-wtc-full", filename: "expected.newrecruit-wtc-full.txt" },
  { format: "newrecruit-simple", filename: "expected.newrecruit-simple.txt" },
];

const JSON_EXPORTS: { format: ExportFormat; filename: string }[] = [
  { format: "newrecruit-json", filename: "expected.newrecruit-json.json" },
  { format: "roster-json", filename: "expected.roster-json.json" },
  { format: "rosterizer", filename: "expected.rosterizer.json" },
];

function inputsFor(caseDir: string): InputDescriptor[] {
  const entries = readdirSync(caseDir);
  const inputs: InputDescriptor[] = [];
  for (const name of entries) {
    if (!name.startsWith("input.")) continue;
    inputs.push({ filename: name, parseAsJson: name.endsWith(".json") });
  }
  return inputs;
}

/**
 * Expected detected format for an `input.*` fixture, by filename convention:
 * - `input.json` is always the bare ListForge BattleScribe payload (no
 *   NewRecruit xmlns/generatedBy markers).
 * - `input.newrecruit-<sub>.<ext>` carries the format id between `input.` and
 *   the extension.
 *
 * Pins the auto-detect contract: every fixture filename is a claim about which
 * adapter must win under {@link tryImportRoster}'s greedy first-match dispatch.
 */
function expectedFormatFor(filename: string): RosterFormat {
  if (filename === "input.json") return "listforge";
  if (filename === "input.rosterizer.json") return "rosterizer";
  if (filename === "input.gw.txt") return "gw";
  const match = /^input\.(newrecruit-[a-z-]+)\.[a-z]+$/.exec(filename);
  if (!match) throw new Error(`unrecognised input fixture filename: ${filename}`);
  return match[1] as RosterFormat;
}

describe("conformance corpus (ties out with the Rust crate)", () => {
  it("normalizeName matches every case in normalize.json", () => {
    const table = readJson(join(CONFORMANCE, "normalize.json")) as {
      input: string;
      expected: string;
    }[];
    expect(table.length).toBeGreaterThan(0);
    for (const { input, expected } of table) {
      expect(normalizeName(input), `normalizeName(${JSON.stringify(input)})`).toBe(expected);
    }
  });

  const ds = Dataset.embedded();
  const rosterDir = join(CONFORMANCE, "roster");
  const cases = readdirSync(rosterDir, { withFileTypes: true }).filter((e) => e.isDirectory());

  it("the roster corpus is non-empty", () => {
    expect(cases.length).toBeGreaterThan(0);
  });

  for (const entry of cases) {
    const caseDir = join(rosterDir, entry.name);
    const expected = readJson(join(caseDir, "expected.roster.json"));
    const inputs = inputsFor(caseDir);

    it(`roster/${entry.name}: tryImportRoster auto-detects the format of every input`, () => {
      expect(inputs.length).toBeGreaterThan(0);
      for (const { filename } of inputs) {
        const raw = readText(join(caseDir, filename));
        const result = tryImportRoster(raw, { dataset: ds });
        if (!result.ok) {
          throw new Error(
            `roster/${entry.name} ${filename}: expected ok, got ${result.reason}: ${result.message}`,
          );
        }
        expect(result.format, `roster/${entry.name} ${filename}`).toBe(
          expectedFormatFor(filename),
        );
      }
    });

    it(`roster/${entry.name}: every input parses to the same Roster`, () => {
      expect(inputs.length).toBeGreaterThan(0);
      for (const { filename, parseAsJson } of inputs) {
        const path = join(caseDir, filename);
        const raw = parseAsJson ? readJson(path) : readText(path);
        const actual = importRoster(raw, { dataset: ds });
        const isCanonical =
          filename === "input.json" ||
          filename === "input.newrecruit-json.json" ||
          filename === "input.gw.txt";
        if (isCanonical) {
          // Canonical seed must reproduce the golden exactly.
          expect(
            JSON.parse(JSON.stringify(actual)),
            `roster/${entry.name} input ${filename}`,
          ).toEqual(expected);
        } else {
          // Derived text inputs are round-trips of the seed through an
          // exporter; format-only fields (`source.format`, `generated_by`,
          // some diagnostics) reshape, but the resolved roster shape — the
          // structural data we *can* round-trip — must still match.
          const stable = (r: unknown) => {
            const x = JSON.parse(JSON.stringify(r)) as Record<string, unknown>;
            delete x.source;
            delete x.diagnostics;
            return x;
          };
          expect(stable(actual), `roster/${entry.name} input ${filename}`).toEqual(stable(expected));
        }
      }
    });

    it(`roster/${entry.name}: every export matches its golden`, () => {
      // The conformance corpus carries export goldens only for the rosters
      // built with the NewRecruit pipeline. Legacy ListForge fixtures don't
      // exercise the exporter (yet), so skip when no goldens are present.
      const allExports = [...TEXT_EXPORTS, ...JSON_EXPORTS];
      const dirEntries = readdirSync(caseDir);
      const present = allExports.filter((e) => dirEntries.includes(e.filename));
      if (present.length === 0) return;

      // Use the canonical seed (input.json, input.newrecruit-json.json, or the
      // text-only input.gw.txt) so the Roster we re-export is deterministic.
      const seed =
        dirEntries.find((n) => n === "input.json") ??
        dirEntries.find((n) => n === "input.newrecruit-json.json") ??
        dirEntries.find((n) => n === "input.gw.txt");
      if (!seed) throw new Error(`no canonical input in roster/${entry.name}`);
      const seedPath = join(caseDir, seed);
      const roster = importRoster(
        seed.endsWith(".json") ? readJson(seedPath) : readText(seedPath),
        { dataset: ds },
      );

      for (const { format, filename } of present) {
        const path = join(caseDir, filename);
        const goldenText = filename.endsWith(".json")
          ? JSON.stringify(readJson(path), null, 2) + "\n"
          : readText(path);
        const actual = exportRoster(roster, format);
        expect(actual, `export ${format} for roster/${entry.name}`).toBe(goldenText);
      }
    });
  }
});

// Cruncher conformance — every case names an attacker/target by id (resolved
// against the embedded dataset), a flat `buffs` stack, an `EngineContext`,
// and an `expected.stages` map of expected-value floats. The runner asserts
// each stage matches within `5e-4` of the golden — wide enough to absorb the
// four-decimal rounding in the goldens themselves, tight enough that any
// non-trivial engine drift is caught.

const CRUNCHER_TOLERANCE = 5e-4;

interface CruncherCase {
  name: string;
  attacker: { weaponId: string; profileIndex: number };
  modelsFiring: number;
  target: { unitId: string; profileIndex: number; modelCount?: number };
  context: EngineContext;
  buffs: Buff[];
  expected: { stages: Record<Stage["name"], number> };
}

// Abilities-resolver conformance — each case names an EligibilityInput, a
// phase, and the expected (kind, abilityId) pairs the resolver should yield
// in the order it yields them. Pins both content and order across runs so a
// Rust port can replay byte-identical.

interface ResolverCase {
  name: string;
  input: EligibilityInput;
  phase: Phase;
  expected: { kind: string; abilityId: string }[];
}

describe("abilities-resolver conformance corpus", () => {
  const ds = Dataset.embedded();
  const dir = join(CONFORMANCE, "abilities-resolver");
  const files = readdirSync(dir)
    .filter((n) => n.endsWith(".json") && !n.endsWith("from-dsl.json"))
    .sort();

  it("the resolver corpus is non-empty", () => {
    expect(files.length).toBeGreaterThan(0);
  });

  for (const filename of files) {
    const c = readJson(join(dir, filename)) as ResolverCase;
    it(`abilities-resolver/${filename}: matches the expected (kind, abilityId) list`, () => {
      const actual = ds
        .eligibleAbilities(c.input, c.phase)
        .map((e) => ({ kind: e.source.kind, abilityId: e.ability.id }));
      expect(actual).toEqual(c.expected);
    });
  }

  type DslCase = {
    abilityId: string;
    source: { kind: "ability"; abilityId: string; abilityKind: string };
    context: EngineContext;
    perspective?: "attacker" | "target";
    expected: {
      applied: unknown[];
      unsupportedReasons: string[];
      /** Opt-in levers behind player gates, projected to id/label/group/buffs. */
      activatable?: unknown[];
    };
  };

  function runDslCorpus(filename: string): void {
    const dsl = readJson(join(dir, filename)) as { cases: DslCase[] };
    for (const c of dsl.cases) {
      const ability = ds.abilities.get(c.abilityId);
      expect(ability, `unknown ability ${c.abilityId}`).toBeDefined();
      const result = effectToBuffs(
        ability!.raw.effect,
        c.source as never,
        c.context,
        c.perspective ?? "attacker",
      );
      const appliedContribs = result.applied.map((b) => b.contribution);
      expect(
        appliedContribs,
        `applied buffs for ${c.abilityId} (${c.perspective ?? "attacker"})`,
      ).toEqual(c.expected.applied);
      const reasons = result.unsupported.map((u) => u.reason);
      expect(
        reasons,
        `unsupported reasons for ${c.abilityId} (${c.perspective ?? "attacker"})`,
      ).toEqual(c.expected.unsupportedReasons);
      if (c.expected.activatable) {
        const acts = result.activatable.map((a) => ({
          id: a.id,
          label: a.label,
          group: a.group ?? null,
          buffs: a.buffs.map((b) => b.contribution),
        }));
        expect(
          acts,
          `activatable levers for ${c.abilityId} (${c.perspective ?? "attacker"})`,
        ).toEqual(c.expected.activatable);
      }
    }
  }

  it("from-dsl.json: every case translates to the expected applied + unsupported", () => {
    runDslCorpus("from-dsl.json");
  });

  it("defensive-from-dsl.json: target-perspective translations match", () => {
    runDslCorpus("defensive-from-dsl.json");
  });
});

describe("cruncher conformance corpus", () => {
  const ds = Dataset.embedded();
  const cruncherDir = join(CONFORMANCE, "cruncher");
  const files = readdirSync(cruncherDir).filter((n) => n.endsWith(".json")).sort();

  it("the cruncher corpus is non-empty", () => {
    expect(files.length).toBeGreaterThan(0);
  });

  for (const filename of files) {
    const path = join(cruncherDir, filename);
    const c = readJson(path) as CruncherCase;
    it(`cruncher/${filename}: stages match the golden within ${CRUNCHER_TOLERANCE}`, () => {
      const weapon = ds.weapons.get(c.attacker.weaponId);
      const unit = ds.units.get(c.target.unitId);
      expect(weapon, `unknown weapon ${c.attacker.weaponId} in ${filename}`).toBeDefined();
      expect(unit, `unknown unit ${c.target.unitId} in ${filename}`).toBeDefined();
      const out = crunch(
        {
          attacker: { weapon: weapon!.raw, profileIndex: c.attacker.profileIndex },
          target: {
            unit: unit!.raw,
            profileIndex: c.target.profileIndex,
            ...(c.target.modelCount !== undefined ? { modelCount: c.target.modelCount } : {}),
          },
          modelsFiring: c.modelsFiring,
          buffs: c.buffs,
          context: c.context,
        },
        ds,
      );
      const actualByName = Object.fromEntries(out.stages.map((s) => [s.name, s.expected])) as Record<
        Stage["name"],
        number
      >;
      for (const [name, expected] of Object.entries(c.expected.stages) as [Stage["name"], number][]) {
        const actual = actualByName[name];
        expect(actual, `stage ${name} missing in ${filename}`).toBeDefined();
        const delta = Math.abs(actual - expected);
        expect(
          delta < CRUNCHER_TOLERANCE,
          `cruncher/${filename} stage ${name}: expected ${expected.toFixed(6)}, got ${actual.toFixed(6)} (Δ ${delta.toFixed(6)})`,
        ).toBe(true);
      }
    });
  }
});
