/**
 * Cross-implementation conformance: the TypeScript reference must keep
 * producing the committed corpus, and the Rust crate asserts against the same
 * files (`crates/wh40kdc/tests/conformance.rs`). The corpus is generated by
 * `npm run gen:conformance`; a CI drift guard keeps it current.
 *
 * Three layers are pinned:
 * 1. `normalizeName` against every entry in `normalize.json`.
 * 2. Every roster fixture: each `input.*` file imports to the same
 *    `expected.roster.json`.
 * 3. Every export target: `exportRoster(roster, fmt)` reproduces each
 *    `expected.<fmt>.{txt,json}` golden byte-for-byte.
 */
import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { Dataset } from "../src/data/dataset.js";
import { normalizeName } from "../src/data/normalize.js";
import { exportRoster, type ExportFormat } from "../src/export/index.js";
import { importRoster } from "../src/import/import-roster.js";

const CONFORMANCE = join(dirname(fileURLToPath(import.meta.url)), "../../conformance");
const readJson = (path: string): unknown => JSON.parse(readFileSync(path, "utf8"));
const readText = (path: string): string => readFileSync(path, "utf8");

interface InputDescriptor {
  filename: string;
  /** When `.json`, parse before importing; when `.txt`, pass the raw string. */
  parseAsJson: boolean;
}

const TEXT_EXPORTS: { format: ExportFormat; filename: string }[] = [
  { format: "newrecruit-wtc-compact", filename: "expected.newrecruit-wtc-compact.txt" },
  { format: "newrecruit-wtc-full", filename: "expected.newrecruit-wtc-full.txt" },
  { format: "newrecruit-simple", filename: "expected.newrecruit-simple.txt" },
];

const JSON_EXPORTS: { format: ExportFormat; filename: string }[] = [
  { format: "newrecruit-json", filename: "expected.newrecruit-json.json" },
  { format: "roster-json", filename: "expected.roster-json.json" },
];

function inputsFor(caseDir: string): InputDescriptor[] {
  const entries = readdirSync(caseDir);
  const inputs: InputDescriptor[] = [];
  for (const name of entries) {
    if (!name.startsWith("input.")) continue;
    inputs.push({ filename: name, parseAsJson: name.endsWith(".json") });
  }
  return inputs;
}

describe("conformance corpus (ties out with the Rust crate)", () => {
  it("normalizeName matches every case in normalize.json", () => {
    const table = readJson(join(CONFORMANCE, "normalize.json")) as {
      input: string;
      expected: string;
    }[];
    expect(table.length).toBeGreaterThan(0);
    for (const { input, expected } of table) {
      expect(normalizeName(input), `normalizeName(${JSON.stringify(input)})`).toBe(expected);
    }
  });

  const ds = Dataset.embedded();
  const rosterDir = join(CONFORMANCE, "roster");
  const cases = readdirSync(rosterDir, { withFileTypes: true }).filter((e) => e.isDirectory());

  it("the roster corpus is non-empty", () => {
    expect(cases.length).toBeGreaterThan(0);
  });

  for (const entry of cases) {
    const caseDir = join(rosterDir, entry.name);
    const expected = readJson(join(caseDir, "expected.roster.json"));
    const inputs = inputsFor(caseDir);

    it(`roster/${entry.name}: every input parses to the same Roster`, () => {
      expect(inputs.length).toBeGreaterThan(0);
      for (const { filename, parseAsJson } of inputs) {
        const path = join(caseDir, filename);
        const raw = parseAsJson ? readJson(path) : readText(path);
        const actual = importRoster(raw, { dataset: ds });
        const isCanonical = filename === "input.json" || filename === "input.newrecruit-json.json";
        if (isCanonical) {
          // Canonical seed must reproduce the golden exactly.
          expect(
            JSON.parse(JSON.stringify(actual)),
            `roster/${entry.name} input ${filename}`,
          ).toEqual(expected);
        } else {
          // Derived text inputs are round-trips of the seed through an
          // exporter; format-only fields (`source.format`, `generated_by`,
          // some diagnostics) reshape, but the resolved roster shape — the
          // structural data we *can* round-trip — must still match.
          const stable = (r: unknown) => {
            const x = JSON.parse(JSON.stringify(r)) as Record<string, unknown>;
            delete x.source;
            delete x.diagnostics;
            return x;
          };
          expect(stable(actual), `roster/${entry.name} input ${filename}`).toEqual(stable(expected));
        }
      }
    });

    it(`roster/${entry.name}: every export matches its golden`, () => {
      // The conformance corpus carries export goldens only for the rosters
      // built with the NewRecruit pipeline. Legacy ListForge fixtures don't
      // exercise the exporter (yet), so skip when no goldens are present.
      const allExports = [...TEXT_EXPORTS, ...JSON_EXPORTS];
      const dirEntries = readdirSync(caseDir);
      const present = allExports.filter((e) => dirEntries.includes(e.filename));
      if (present.length === 0) return;

      // Use the canonical seed (input.json or input.newrecruit-json.json) so
      // the Roster we re-export is deterministic.
      const seed =
        dirEntries.find((n) => n === "input.json") ??
        dirEntries.find((n) => n === "input.newrecruit-json.json");
      if (!seed) throw new Error(`no canonical JSON input in roster/${entry.name}`);
      const roster = importRoster(readJson(join(caseDir, seed)), { dataset: ds });

      for (const { format, filename } of present) {
        const path = join(caseDir, filename);
        const goldenText = filename.endsWith(".json")
          ? JSON.stringify(readJson(path), null, 2) + "\n"
          : readText(path);
        const actual = exportRoster(roster, format);
        expect(actual, `export ${format} for roster/${entry.name}`).toBe(goldenText);
      }
    });
  }
});
