//! Cross-implementation conformance: the Rust crate must reproduce the
//! reference (TypeScript) outputs byte-for-byte (structurally).
//!
//! Both implementations assert against one committed corpus under repo-root
//! `conformance/`, generated by the TS reference (`npm run gen:conformance`).
//! The TS suite (`tools/test/conformance.test.ts`) asserts the same files, and
//! a CI drift guard keeps the goldens current — so a lookup or import that
//! resolves in TS resolves identically here. This is where the two toolchains
//! tie out.
//!
//! Three layers are pinned (matches the TS test):
//! 1. `normalize_name` against every entry in `normalize.json`.
//! 2. Every roster fixture: each `input.*` file imports to the same
//!    `expected.roster.json` (canonical seeds match exactly; derived text
//!    inputs match after stripping `source` + `diagnostics`).
//! 3. Every export target: `export_roster(roster, fmt)` reproduces each
//!    `expected.<fmt>.{txt,json}` golden byte-for-byte.

#![cfg(feature = "import")]

use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;
use wh40kdc::import::{
    import_roster, import_roster_text, select_adapter, try_import_roster, FormatAdapter, GwAdapter,
    ImportResult, ListForgeAdapter, ListForgeTextAdapter, NewRecruitJsonAdapter,
    NewRecruitSimpleAdapter, NewRecruitWtcCompactAdapter, NewRecruitWtcFullAdapter, RosterFormat,
    RosterizerAdapter,
};
use wh40kdc::{normalize_name, Dataset};

/// Adapter registry in the same priority order as `import_roster` uses
/// internally. Tests need this to drive the parsed stage directly without
/// going through resolve.
fn conformance_adapters() -> Vec<Box<dyn FormatAdapter>> {
    vec![
        Box::new(RosterizerAdapter),
        Box::new(NewRecruitJsonAdapter),
        Box::new(GwAdapter),
        Box::new(NewRecruitWtcFullAdapter),
        Box::new(NewRecruitWtcCompactAdapter),
        Box::new(NewRecruitSimpleAdapter),
        Box::new(ListForgeTextAdapter),
        Box::new(ListForgeAdapter),
    ]
}

#[cfg(feature = "export")]
use wh40kdc::export::{export_roster, ExportFormat};

fn conformance_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../conformance")
}

fn read_json(path: &Path) -> Value {
    let raw =
        fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("corpus file is valid JSON")
}

fn read_text(path: &Path) -> String {
    fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
}

/// Strip the fields that legitimately vary across format hops (the
/// `source.format` + `generated_by`, and the diagnostics produced during
/// import). Mirrors the TS `stable()` helper in `tools/test/conformance.test.ts`.
fn stable(value: &Value) -> Value {
    let mut copy = value.clone();
    if let Some(obj) = copy.as_object_mut() {
        obj.remove("source");
        obj.remove("diagnostics");
    }
    copy
}

fn case_dirs(roster_dir: &Path) -> Vec<PathBuf> {
    let mut out: Vec<PathBuf> = fs::read_dir(roster_dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", roster_dir.display()))
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    out.sort();
    out
}

fn list_files(dir: &Path) -> Vec<String> {
    let mut out: Vec<String> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
        .filter_map(Result::ok)
        .filter_map(|e| e.file_name().into_string().ok())
        .collect();
    out.sort();
    out
}

#[test]
fn normalize_name_matches_reference_corpus() {
    let table = read_json(&conformance_dir().join("normalize.json"));
    let cases = table.as_array().expect("normalize.json is an array");
    assert!(!cases.is_empty(), "normalize corpus is empty");

    for case in cases {
        let input = case["input"].as_str().expect("case.input is a string");
        let expected = case["expected"]
            .as_str()
            .expect("case.expected is a string");
        assert_eq!(
            normalize_name(input),
            expected,
            "normalize_name({input:?}) diverged from the TS reference"
        );
    }
}

/// Expected detected format for an `input.*` fixture, by filename convention.
/// Mirrors `expectedFormatFor` in `tools/test/conformance.test.ts`.
fn expected_format_for(filename: &str) -> RosterFormat {
    if filename == "input.json" {
        return RosterFormat::Listforge;
    }
    let stem = filename
        .strip_prefix("input.")
        .and_then(|s| s.rsplit_once('.').map(|(left, _ext)| left))
        .unwrap_or_else(|| panic!("unrecognised input fixture filename: {filename}"));
    match stem {
        "newrecruit-json" => RosterFormat::NewrecruitJson,
        "newrecruit-wtc-compact" => RosterFormat::NewrecruitWtcCompact,
        "newrecruit-wtc-full" => RosterFormat::NewrecruitWtcFull,
        "newrecruit-simple" => RosterFormat::NewrecruitSimple,
        "rosterizer" => RosterFormat::Rosterizer,
        "gw" => RosterFormat::Gw,
        "listforge-text" => RosterFormat::ListforgeText,
        other => panic!("unmapped input fixture stem: {other}"),
    }
}

#[test]
fn try_import_roster_detects_format_of_every_fixture() {
    let ds = Dataset::embedded();
    let roster_dir = conformance_dir().join("roster");
    let cases = case_dirs(&roster_dir);
    assert!(!cases.is_empty(), "no roster conformance cases found");

    for case_dir in &cases {
        let case_name = case_dir.file_name().and_then(|s| s.to_str()).unwrap_or("?");
        let mut inputs: Vec<String> = list_files(case_dir)
            .into_iter()
            .filter(|n| n.starts_with("input."))
            .collect();
        inputs.sort();
        assert!(!inputs.is_empty(), "roster/{case_name}: no input.* files");

        for filename in &inputs {
            let path = case_dir.join(filename);
            let raw = read_text(&path);
            let expected = expected_format_for(filename);
            match try_import_roster(&raw, ds) {
                ImportResult::Ok { format, .. } => assert_eq!(
                    format, expected,
                    "roster/{case_name} {filename}: auto-detected {format:?}, expected {expected:?}"
                ),
                ImportResult::Err {
                    reason, message, ..
                } => panic!(
                    "roster/{case_name} {filename}: try_import_roster errored {reason:?}: {message}"
                ),
            }
        }
    }
}

#[test]
fn imported_rosters_match_reference_goldens() {
    let ds = Dataset::embedded();
    let roster_dir = conformance_dir().join("roster");
    let cases = case_dirs(&roster_dir);
    assert!(!cases.is_empty(), "no roster conformance cases found");

    let mut total_inputs = 0;
    for case_dir in &cases {
        let expected = read_json(&case_dir.join("expected.roster.json"));
        let case_name = case_dir.file_name().and_then(|s| s.to_str()).unwrap_or("?");

        let mut inputs: Vec<String> = list_files(case_dir)
            .into_iter()
            .filter(|n| n.starts_with("input."))
            .collect();
        inputs.sort();
        assert!(
            !inputs.is_empty(),
            "roster/{case_name}: no input.* files in corpus directory"
        );

        for filename in &inputs {
            let path = case_dir.join(filename);
            let actual = if filename.ends_with(".json") {
                import_roster(&read_json(&path), ds)
            } else {
                import_roster_text(&read_text(&path), ds)
            }
            .unwrap_or_else(|e| panic!("import roster/{case_name} {filename}: {e}"));

            let actual_value = serde_json::to_value(&actual).expect("Roster serializes to a Value");

            let is_canonical = filename == "input.json"
                || filename == "input.newrecruit-json.json"
                || filename == "input.gw.txt"
                || filename == "input.listforge-text.txt";
            if is_canonical {
                assert_eq!(
                    actual_value, expected,
                    "roster/{case_name} input {filename} diverged from the TS golden"
                );
            } else {
                assert_eq!(
                    stable(&actual_value),
                    stable(&expected),
                    "roster/{case_name} input {filename} diverged from the TS golden \
                     (source/diagnostics excluded)"
                );
            }
            total_inputs += 1;
        }
    }

    assert!(total_inputs > 0, "no roster inputs exercised");
}

#[test]
fn parsed_stage_matches_reference_goldens() {
    let roster_dir = conformance_dir().join("roster");
    let cases = case_dirs(&roster_dir);
    assert!(!cases.is_empty(), "no roster conformance cases found");

    let registry = conformance_adapters();
    for case_dir in &cases {
        let case_name = case_dir.file_name().and_then(|s| s.to_str()).unwrap_or("?");
        let dir_entries = list_files(case_dir);

        // Pick the canonical seed (matches gen-conformance's decodeCanonicalSeed).
        let (decoded, seed_name): (Value, &str) = if dir_entries.iter().any(|n| n == "input.json") {
            (read_json(&case_dir.join("input.json")), "input.json")
        } else if dir_entries
            .iter()
            .any(|n| n == "input.newrecruit-json.json")
        {
            (
                read_json(&case_dir.join("input.newrecruit-json.json")),
                "input.newrecruit-json.json",
            )
        } else if dir_entries.iter().any(|n| n == "input.gw.txt") {
            (
                Value::String(read_text(&case_dir.join("input.gw.txt"))),
                "input.gw.txt",
            )
        } else if dir_entries.iter().any(|n| n == "input.listforge-text.txt") {
            (
                Value::String(read_text(&case_dir.join("input.listforge-text.txt"))),
                "input.listforge-text.txt",
            )
        } else {
            panic!("roster/{case_name}: no canonical seed");
        };

        let adapter = select_adapter(&decoded, &registry)
            .unwrap_or_else(|e| panic!("roster/{case_name} {seed_name}: select_adapter: {e}"));
        let parsed = adapter
            .parse(&decoded)
            .unwrap_or_else(|e| panic!("roster/{case_name} {seed_name}: parse: {e}"));

        let actual = serde_json::to_value(&parsed).expect("ParsedRoster serializes to a Value");
        let expected = read_json(&case_dir.join("expected.parsed.json"));
        assert_eq!(
            actual, expected,
            "roster/{case_name}: parsed stage diverged from the TS golden"
        );
    }
}

#[cfg(feature = "export")]
#[test]
fn exported_rosters_match_reference_goldens() {
    use serde_json::ser::PrettyFormatter;

    let ds = Dataset::embedded();
    let roster_dir = conformance_dir().join("roster");
    let cases = case_dirs(&roster_dir);
    assert!(!cases.is_empty(), "no roster conformance cases found");

    const TEXT_EXPORTS: &[(ExportFormat, &str)] = &[
        (
            ExportFormat::NewrecruitWtcCompact,
            "expected.newrecruit-wtc-compact.txt",
        ),
        (
            ExportFormat::NewrecruitWtcFull,
            "expected.newrecruit-wtc-full.txt",
        ),
        (
            ExportFormat::NewrecruitSimple,
            "expected.newrecruit-simple.txt",
        ),
    ];
    const JSON_EXPORTS: &[(ExportFormat, &str)] = &[
        (
            ExportFormat::NewrecruitJson,
            "expected.newrecruit-json.json",
        ),
        (ExportFormat::RosterJson, "expected.roster-json.json"),
        (ExportFormat::Rosterizer, "expected.rosterizer.json"),
    ];

    let mut total_assertions = 0;
    for case_dir in &cases {
        let case_name = case_dir.file_name().and_then(|s| s.to_str()).unwrap_or("?");
        let files = list_files(case_dir);

        let present_text: Vec<_> = TEXT_EXPORTS
            .iter()
            .filter(|(_, f)| files.iter().any(|n| n == f))
            .collect();
        let present_json: Vec<_> = JSON_EXPORTS
            .iter()
            .filter(|(_, f)| files.iter().any(|n| n == f))
            .collect();

        if present_text.is_empty() && present_json.is_empty() {
            continue;
        }

        let seed_filename = files
            .iter()
            .find(|n| n.as_str() == "input.json")
            .or_else(|| {
                files
                    .iter()
                    .find(|n| n.as_str() == "input.newrecruit-json.json")
            })
            .or_else(|| files.iter().find(|n| n.as_str() == "input.gw.txt"))
            .or_else(|| {
                files
                    .iter()
                    .find(|n| n.as_str() == "input.listforge-text.txt")
            })
            .unwrap_or_else(|| {
                panic!("roster/{case_name}: export goldens present but no canonical input")
            });
        let seed_path = case_dir.join(seed_filename);
        let roster = if seed_filename.ends_with(".json") {
            import_roster(&read_json(&seed_path), ds)
        } else {
            import_roster_text(&read_text(&seed_path), ds)
        }
        .unwrap_or_else(|e| panic!("seed import roster/{case_name}: {e}"));

        for (fmt, filename) in &present_text {
            let golden = read_text(&case_dir.join(filename));
            let actual = export_roster(&roster, *fmt);
            assert_eq!(
                actual, golden,
                "export {filename} for roster/{case_name} diverged from the TS golden"
            );
            total_assertions += 1;
        }

        for (fmt, filename) in &present_json {
            // Re-serialize the on-disk JSON through serde_json's pretty
            // formatter so any whitespace/quoting differences are normalised
            // — the contract is "same Value tree", not byte-equality of
            // possibly-CRLF goldens.
            let golden_value = read_json(&case_dir.join(filename));
            let mut buf: Vec<u8> = Vec::with_capacity(1024);
            let formatter = PrettyFormatter::with_indent(b"  ");
            let mut ser = serde_json::Serializer::with_formatter(&mut buf, formatter);
            serde::Serialize::serialize(&golden_value, &mut ser).expect("golden re-serializes");
            buf.push(b'\n');
            let golden_text = String::from_utf8(buf).expect("golden is UTF-8");

            let actual = export_roster(&roster, *fmt);
            assert_eq!(
                actual, golden_text,
                "export {filename} for roster/{case_name} diverged from the TS golden"
            );
            total_assertions += 1;
        }
    }

    assert!(total_assertions > 0, "no export goldens exercised");
}
