/**
 * Terrain sets: editor-only macros that stamp a recurring area + parented feature
 * composition in one action. Purely an authoring affordance — the exported JSON is
 * ordinary pieces, indistinguishable from hand-placed ones.
 *
 * A set declares **seats**, not coordinates. Every one of the 69 feature placements
 * captured from Battlemaster's composites is reproduced to ≤0.005″ by one rule —
 * seat the feature's oriented bounding box into a corner of the area's artwork
 * rectangle with an inset (see the plate-seating section of `model.ts`) — so the
 * sets go through `resolveSetFeature`, the same function interactive seating uses.
 * That is why there are 7 entries here and not a 27-row coordinate table: the
 * remaining arrangements are generated by dropping a corner piece near an area
 * corner, and a declared seat cannot go stale when a plate is re-measured.
 *
 * Only the first four are *necessary* — the rule cannot generate a centred or a
 * flush-to-edge feature. The last three are convenience: pure corner seats, kept
 * because they appear in every single one of the 46 committed layouts.
 *
 * Seats are resolved in the parent area's centroid-local frame — the convention
 * the resolver and `parent_area_id` use — so *moving* the area carries the whole
 * set. **Rotating it does not**: `orientPiece` deliberately pins child features in
 * board space (it changes only the area's own shape), so rotating a stamped area
 * turns the plate out from under its features and breaks the seat. Re-seat the
 * children afterwards, or author the rotation on the set.
 */
import type { FeatureSeat, Mirror } from "./model.js";

export interface SetFeatureDef {
  template: string;
  /** Rotation in the parent area's local frame. */
  rotation: number;
  mirror?: Mirror;
  /** Where in the area's plate (artwork) rectangle the feature seats. */
  seat: FeatureSeat;
}

export interface TerrainSetDef {
  id: string;
  name: string;
  area: { template: string; rotation?: number };
  features: SetFeatureDef[];
}

/** Flush on x, Battlemaster's 0.5″ on y — the `area-long-line` barricades only. */
const FLUSH_X = { x: 0, y: 0.5 };

export const TERRAIN_SETS: TerrainSetDef[] = [
  // ── centred / flush features: the four the seat rule can't generate ──────────
  {
    id: "generator-pad",
    name: "Generator pad",
    area: { template: "area-medium" },
    // r180, not r90: the generator is 4.5 × 2.0, so at 90° it stands 4.5″ tall
    // inside a 4.0″ plate and overflows it.
    features: [{ template: "generator", rotation: 180, seat: { kind: "centred" } }],
  },
  {
    id: "pipe-strip",
    name: "Pipe strip",
    area: { template: "area-short-line" },
    features: [{ template: "pipe", rotation: 180, seat: { kind: "centred" } }],
  },
  {
    id: "catwalk-strip",
    name: "Catwalk strip",
    area: { template: "area-short-line" },
    features: [{ template: "catwalk", rotation: 180, seat: { kind: "centred" } }],
  },
  {
    id: "gantry-strip",
    name: "Gantry strip",
    area: { template: "area-long-line" },
    features: [
      { template: "barricade", rotation: 0, seat: { kind: "corner", corner: "top-left", inset: FLUSH_X } },
      { template: "barricade", rotation: 0, seat: { kind: "corner", corner: "top-right", inset: FLUSH_X } },
      { template: "gantry", rotation: 0, seat: { kind: "centred" } },
    ],
  },

  // ── pure corner seats, kept for one-click convenience (uses=90 each) ─────────
  {
    id: "ruin-corners-medium",
    name: "Medium ruin corners",
    area: { template: "area-medium" },
    features: [
      { template: "corner-short", rotation: 180, mirror: "horizontal", seat: { kind: "corner", corner: "top-left" } },
      { template: "corner-short", rotation: 0, mirror: "horizontal", seat: { kind: "corner", corner: "bottom-right" } },
    ],
  },
  {
    id: "ruin-trapezoid-bottom",
    name: "Trapezoid ruin — bottom",
    area: { template: "area-trapezoid" },
    features: [
      { template: "corner-ruin-balanced-left", rotation: 0, seat: { kind: "corner", corner: "bottom-left" } },
      { template: "corner-tiny", rotation: 180, seat: { kind: "corner", corner: "top-left" } },
    ],
  },
  {
    id: "ruin-trapezoid-top",
    name: "Trapezoid ruin — top",
    area: { template: "area-trapezoid" },
    features: [
      { template: "corner-ruin-balanced-left", rotation: 90, seat: { kind: "corner", corner: "top-left" } },
      { template: "corner-tiny", rotation: 90, seat: { kind: "corner", corner: "bottom-left" } },
    ],
  },
];
