#!/usr/bin/env python3
"""Generate TypedDict entity types from the bundled JSON Schema.

Runs datamodel-code-generator against
``crates/wh40kdc/schemas/bundled.schema.json`` (the same artifact Rust's
typify codegen consumes, produced by ``npm run bundle:schemas`` in tools/).
The output is a typing aid only — runtime values are plain dicts, mirroring
the TypeScript reference implementation.

``--no-use-closed-typed-dict`` keeps the output importable with the stdlib
``typing`` module alone (PEP 728 ``closed=True`` would require
typing_extensions at runtime); ``--disable-timestamp`` keeps regeneration
byte-stable for the CI drift check.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA = REPO_ROOT / "crates" / "wh40kdc" / "schemas" / "bundled.schema.json"
OUT = REPO_ROOT / "python" / "src" / "wh40kdc" / "_types.py"


def main() -> int:
    if not SCHEMA.exists():
        print(
            f"missing {SCHEMA}; run `cd tools && npm run bundle:schemas` first",
            file=sys.stderr,
        )
        return 1
    cmd = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(SCHEMA),
        "--input-file-type",
        "jsonschema",
        "--output-model-type",
        "typing.TypedDict",
        "--output",
        str(OUT),
        "--target-python-version",
        "3.11",
        "--class-name",
        "BundledSchemas",
        "--no-use-closed-typed-dict",
        "--disable-timestamp",
        "--formatters",
        "ruff-format",
        "--custom-file-header",
        "# Generated by codegen/gen_typeddicts.py — do not edit. CI fails on drift.",
    ]
    # Force UTF-8 output regardless of host locale: datamodel-code-generator writes
    # with the platform default otherwise, mangling the non-ASCII header on Windows
    # (cp1252) into invalid UTF-8 that breaks importing the package.
    subprocess.run(cmd, check=True, env={**os.environ, "PYTHONUTF8": "1"})
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
