#!/usr/bin/env python3
"""Embed conformance/SPEC_VERSION as a generated constant.

The TS and Rust runners parent-walk to ``conformance/SPEC_VERSION`` at
runtime; published Python wheels don't ship the repo, so the version is baked
in at codegen time and drift-checked in CI.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SPEC_FILE = REPO_ROOT / "conformance" / "SPEC_VERSION"
OUT = REPO_ROOT / "python" / "src" / "wh40kdc" / "_spec.py"

TEMPLATE = '''"""Generated by codegen/sync_spec.py — do not edit.

Mirrors conformance/SPEC_VERSION; CI fails on drift.
"""

SPEC_VERSION = {version}
'''


def main() -> int:
    version = int(SPEC_FILE.read_text(encoding="utf-8").strip())
    OUT.write_text(TEMPLATE.format(version=version), encoding="utf-8")
    print(f"wrote {OUT} (SPEC_VERSION = {version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
