#!/usr/bin/env python3
"""Sync the embedded data bundle and schema tree into the Python package.

The bundle is a byte-for-byte copy of the Rust crate's
``crates/wh40kdc/src/data/bundle.generated.json`` (itself regenerated by
``cargo run -p xtask -- bundle-data``). Copying — rather than re-deriving from
``data/`` — guarantees all three implementations share one bundler's file-walk
iteration order, which the set-semantics linked-api conformance queries depend
on (see CONFORMANCE.md).

The schema tree is copied because published wheels don't ship the repo's
``schemas/`` directory; the validator loads the packaged copy.

CI regenerates both and fails on drift (``git diff --exit-code``).
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
RUST_BUNDLE = REPO_ROOT / "crates" / "wh40kdc" / "src" / "data" / "bundle.generated.json"
SCHEMAS_ROOT = REPO_ROOT / "schemas"
SHARE_REGISTRY = REPO_ROOT / "data" / "share-registry.json"
PKG_ROOT = REPO_ROOT / "python" / "src" / "wh40kdc"
PKG_BUNDLE = PKG_ROOT / "_bundle.json"
PKG_SHARE_REGISTRY = PKG_ROOT / "_share_registry.json"
PKG_SCHEMAS = PKG_ROOT / "schemas"


def main() -> int:
    if not RUST_BUNDLE.exists():
        print(
            f"missing {RUST_BUNDLE}; run `cargo run -p xtask -- bundle-data` first",
            file=sys.stderr,
        )
        return 1

    PKG_BUNDLE.write_bytes(RUST_BUNDLE.read_bytes())
    print(f"wrote {PKG_BUNDLE} ({PKG_BUNDLE.stat().st_size} bytes)")

    # The committed share-token id registry, embedded so the share codec works
    # in published wheels (which don't ship the repo's data/ tree).
    if SHARE_REGISTRY.exists():
        PKG_SHARE_REGISTRY.write_bytes(SHARE_REGISTRY.read_bytes())
        print(f"wrote {PKG_SHARE_REGISTRY} ({PKG_SHARE_REGISTRY.stat().st_size} bytes)")

    if PKG_SCHEMAS.exists():
        shutil.rmtree(PKG_SCHEMAS)
    count = 0
    for src in sorted(SCHEMAS_ROOT.rglob("*.schema.json")):
        rel = src.relative_to(SCHEMAS_ROOT)
        dest = PKG_SCHEMAS / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(src.read_bytes())
        count += 1
    print(f"copied {count} schema files into {PKG_SCHEMAS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
