# Generated by codegen/gen_typeddicts.py — do not edit. CI fails on drift.

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypeAlias, TypedDict, Union


BundledSchemas: TypeAlias = Any


EntityId: TypeAlias = str


Edition: TypeAlias = str


DataslateVersion: TypeAlias = str


Keyword: TypeAlias = str


KeywordList: TypeAlias = list[Keyword]


StatValue: TypeAlias = int | str


ContributorRef: TypeAlias = str


class ExternalReference(TypedDict):
    namespace: str
    id: str


ExternalReferenceList: TypeAlias = list[ExternalReference]


Phase: TypeAlias = Literal["command", "movement", "shooting", "charge", "fight"]


PhaseList: TypeAlias = list[Phase]


SourceType: TypeAlias = Literal[
    "ability", "stratagem", "enhancement", "detachment-rule", "faction-rule"
]


PlayerTurn: TypeAlias = Literal["your-turn", "opponent-turn", "either"]


GameEvent: TypeAlias = Literal[
    "start-of-phase",
    "end-of-phase",
    "start-of-turn",
    "end-of-turn",
    "start-of-opponent-turn",
    "end-of-opponent-turn",
    "start-of-battle-round",
    "start-of-command-phase",
    "declare-battle-formations",
    "post-deployment",
    "unit-set-up",
    "set-up-from-reserves",
    "arrives-from-strategic-reserves",
    "starts-in-strategic-reserves",
    "game-start-in-reserves",
    "deep-strike-setup",
    "reinforcements",
    "normal-move",
    "advance-move",
    "advances",
    "fall-back-move",
    "falls-back",
    "charge-move",
    "end-of-charge-move",
    "charge-declaration",
    "moved-through-terrain",
    "moved-through-tall-terrain",
    "enemy-unit-ended-move",
    "enemy-unit-fell-back",
    "before-hit-roll",
    "after-hit-roll",
    "before-wound-roll",
    "after-wound-roll",
    "attack-scores-wound",
    "before-save-roll",
    "after-save-roll",
    "before-damage-roll",
    "after-damage-roll",
    "before-charge-roll",
    "after-charge-roll",
    "before-advance-roll",
    "after-advance-roll",
    "before-battle-shock",
    "after-battle-shock",
    "on-unit-selected",
    "selected-to-shoot",
    "selected-to-fight",
    "selected-to-advance",
    "after-unit-resolves-attacks",
    "after-scoring-hit",
    "after-enemy-unit-fires",
    "on-unit-destroyed",
    "on-model-destroyed",
    "first-model-destroyed",
    "before-bearer-removed",
    "enemy-unit-destroyed-in-melee",
    "on-damage-allocated",
    "battle-shock-test",
    "leadership-test",
    "desperate-escape-test",
    "stratagem-targeted",
    "ability-target-selected",
    "end-of-opponent-charge-phase",
    "enemy-unit-completed-shooting-targeting-bearer",
    "enemy-unit-selects-bearer-as-charge-target",
    "enemy-unit-targets-bearer",
    "enemy-unit-completed-fall-back-from-bearer",
    "act-of-faith-completed",
    "act-of-faith-performed",
    "miracle-die-generated",
    "enemy-unit-selected-charge-targets-before-charge-move",
]


BattleSize: TypeAlias = Literal["incursion", "strike-force"]


ForceDispositionId: TypeAlias = Literal[
    "take-and-hold", "disruption", "purge-the-foe", "priority-assets", "reconnaissance"
]


GameModeId: TypeAlias = Literal["matched-play", "combat-patrol", "boarding-actions", "crusade"]


GameModes: TypeAlias = list[GameModeId]


class Vec2(TypedDict):
    x: float
    y: float


class Footprint1(TypedDict):
    type: Literal["rectangle"]
    width: float
    height: float


class Footprint2(TypedDict):
    type: Literal["right-triangle"]
    width: float
    height: float


class Footprint3(TypedDict):
    type: Literal["polygon"]
    points: list[Vec2]


Footprint: TypeAlias = Footprint1 | Footprint2 | Footprint3


class Wall(TypedDict):
    points: list[Vec2]
    thickness: NotRequired[float]


TerrainAreaKeyword: TypeAlias = Literal["obscuring", "hidden", "plunging-fire"]


class BaseSize(TypedDict):
    shape: Literal["round", "oval", "flying-base", "hull", "unique"]
    diameter: NotRequired[float]
    width: NotRequired[float]
    length: NotRequired[float]
    size: NotRequired[Literal["small", "large"]]
    draft: NotRequired[bool]


class GameVersionRef(TypedDict):
    edition: Edition
    dataslate: DataslateVersion


class AlliedPointsLimit(TypedDict):
    battle_size: Literal["incursion", "strike-force", "onslaught"]
    max_points: int


class AlliedKeywordLimit(TypedDict):
    keyword: Keyword
    battle_size: Literal["incursion", "strike-force", "onslaught"]
    max_count: int


class AlliedRule(TypedDict):
    id: EntityId
    name: str
    label: NotRequired[str]
    army_keywords_any: NotRequired[KeywordList]
    detachment_ids: NotRequired[list[EntityId]]
    source_faction_id: NotRequired[EntityId | None]
    source_keywords: NotRequired[KeywordList]
    source_datasheet_ids: NotRequired[list[EntityId]]
    required_keywords: NotRequired[KeywordList]
    excluded_keywords: NotRequired[KeywordList]
    roles: NotRequired[list[str]]
    points_limits: NotRequired[list[AlliedPointsLimit]]
    keyword_limits: NotRequired[list[AlliedKeywordLimit]]
    max_units: NotRequired[int | None]
    cannot_be_warlord: NotRequired[bool]
    cannot_take_enhancements: NotRequired[bool]
    warlord_required_keyword: NotRequired[Keyword | None]
    warlord_datasheet_ids: NotRequired[list[EntityId]]
    removes_ability_ids: NotRequired[list[EntityId]]
    battleline_ratio_keywords: NotRequired[KeywordList]
    game_version: GameVersionRef
    notes: NotRequired[str]


class ZoneShape1(TypedDict):
    type: Literal["rectangle"]
    width: float
    height: float


class ZoneShape2(TypedDict):
    type: Literal["polygon"]
    points: list[Vec2]


ZoneShape: TypeAlias = ZoneShape1 | ZoneShape2


Side: TypeAlias = Literal["attacker", "defender"]


class Zone(TypedDict):
    player: Side
    name: NotRequired[str]
    shape: ZoneShape
    position: Vec2
    color: NotRequired[str]


class Territory(TypedDict):
    player: Side
    shape: ZoneShape
    position: Vec2


class DeploymentPattern(TypedDict):
    id: EntityId
    name: str
    source: NotRequired[str]
    description: NotRequired[str]
    zones: list[Zone]
    territories: NotRequired[list[Territory]]
    objectives: NotRequired[list[Vec2]]
    recommended_terrain_layout_ids: NotRequired[list[EntityId]]
    game_version: GameVersionRef


class GrantedKeyword(TypedDict):
    keyword: Keyword
    to_keywords: KeywordList
    max_selected: NotRequired[int]


class UnitMinimum(TypedDict):
    keyword: Keyword
    min: int


class Restrictions(TypedDict):
    required_keywords: NotRequired[KeywordList]
    excluded_keywords: NotRequired[KeywordList]
    notes: NotRequired[str]


class Detachment(TypedDict):
    id: EntityId
    external_refs: NotRequired[ExternalReferenceList]
    name: str
    faction_id: EntityId
    detachment_rule_id: NotRequired[EntityId | None]
    detachment_rule_ids: NotRequired[list[EntityId]]
    detachment_points: NotRequired[int | None]
    force_dispositions: NotRequired[list[EntityId]]
    tags: NotRequired[list[str]]
    enhancement_ids: NotRequired[list[EntityId]]
    stratagem_ids: NotRequired[list[EntityId]]
    restrictions: NotRequired[Restrictions | None]
    granted_keywords: NotRequired[list[GrantedKeyword]]
    unit_minimums: NotRequired[list[UnitMinimum]]
    game_version: GameVersionRef
    game_modes: NotRequired[GameModes]


KeywordRestrictionGroup: TypeAlias = list[Keyword]


class Enhancement(TypedDict):
    id: EntityId
    external_refs: NotRequired[ExternalReferenceList]
    name: str
    detachment_id: EntityId
    cost: int
    points_provisional: NotRequired[bool]
    upgrade_tag: NotRequired[bool]
    max_targets: NotRequired[int]
    keyword_restrictions: NotRequired[KeywordList]
    keyword_restriction_groups: NotRequired[list[KeywordRestrictionGroup]]
    exclusion_keywords: NotRequired[KeywordList | None]
    attachment_bodyguard_ids: NotRequired[list[EntityId]]
    ability_id: NotRequired[EntityId | None]
    is_unique: NotRequired[bool]
    game_version: GameVersionRef
    game_modes: NotRequired[GameModes]


class Faction(TypedDict):
    id: EntityId
    external_refs: NotRequired[ExternalReferenceList]
    name: str
    parent_faction_id: NotRequired[EntityId | None]
    game_version: GameVersionRef
    keywords: NotRequired[KeywordList]
    aliases: NotRequired[list[str]]
    faction_rule_ids: list[EntityId]
    logo_url: NotRequired[str]


class ForceDisposition(TypedDict):
    id: ForceDispositionId
    name: str
    text: NotRequired[str]
    game_version: GameVersionRef


class GameMode(TypedDict):
    id: GameModeId
    name: str
    description: NotRequired[str]
    is_competitive: bool
    game_version: GameVersionRef


class GameVersion(TypedDict):
    edition: Edition
    dataslate: DataslateVersion
    effective_date: str
    label: NotRequired[str]
    supersedes: NotRequired[DataslateVersion | None]


class HullShape(TypedDict):
    id: EntityId
    name: str
    points: list[Vec2]
    bounds_width_in: float
    bounds_height_in: float
    game_version: GameVersionRef


EligibleBodyguardKeyword: TypeAlias = str


class LeaderAttachment(TypedDict):
    leader_id: EntityId
    eligible_bodyguard_ids: list[EntityId]
    eligible_bodyguard_keywords: NotRequired[list[EligibleBodyguardKeyword]]
    game_version: GameVersionRef


class MissionMatchup(TypedDict):
    id: EntityId
    disposition: ForceDispositionId
    opponent_disposition: ForceDispositionId
    mission_id: EntityId
    game_version: GameVersionRef


class Mission(TypedDict):
    id: EntityId
    name: str
    source: NotRequired[str]
    description: NotRequired[str]
    vp_per_game_cap: NotRequired[int]
    vp_per_round_cap: NotRequired[int]
    secondary_vp_per_game_cap: NotRequired[int]
    secondary_vp_per_round_cap: NotRequired[int]
    deployment_pattern_ids: NotRequired[list[EntityId]]
    game_version: GameVersionRef


class BattleRound(TypedDict):
    min: NotRequired[int]
    max: NotRequired[int]


class ScoringTrigger(TypedDict):
    phase: NotRequired[Phase]
    timing: NotRequired[
        Literal["start-of-turn", "end-of-turn", "start-of-phase", "end-of-phase", "end-of-battle"]
    ]
    player_turn: NotRequired[PlayerTurn]
    battle_round: NotRequired[BattleRound]


class UnitFilter(TypedDict):
    model_count_min: NotRequired[int]
    model_count_max: NotRequired[int]
    wounds_min: NotRequired[int]
    keywords: NotRequired[KeywordList]


class ArmyCompositionPredicate(TypedDict):
    subject: Literal["self", "opponent"]
    quantifier: Literal["any", "none"]
    unit_filter: UnitFilter


class WhenDrawn(TypedDict):
    operation: Literal["reshuffle", "replace", "redraw", "draw-extra", "swap"]
    card_ids: NotRequired[list[EntityId]]
    condition: NotRequired[ArmyCompositionPredicate]
    battle_round: NotRequired[BattleRound]


class TargetRestrictions(TypedDict):
    required_keywords: NotRequired[KeywordList]
    required_keywords_any: NotRequired[KeywordList]
    excluded_keywords: NotRequired[KeywordList]
    notes: NotRequired[str]


class Stratagem(TypedDict):
    id: EntityId
    external_refs: NotRequired[ExternalReferenceList]
    name: str
    category: Literal["core", "detachment"]
    type: NotRequired[Literal["battle-tactic", "strategic-ploy", "epic-deed", "wargear"]]
    detachment_id: NotRequired[EntityId | None]
    cp_cost: int
    phases: PhaseList
    player_turn: PlayerTurn
    timing: Literal["once-per-phase", "once-per-turn", "once-per-battle", "unlimited"]
    target_restrictions: NotRequired[TargetRestrictions | None]
    ability_id: NotRequired[EntityId | None]
    game_version: GameVersionRef
    game_modes: NotRequired[GameModes]


class TargetProfile(TypedDict):
    id: EntityId
    name: str
    description: NotRequired[str]
    faction_id: EntityId
    unit_id: EntityId
    model_count_override: NotRequired[int | None]
    game_version: GameVersionRef


class Objective(TypedDict):
    position: NotRequired[Vec2]
    control_range_inches: NotRequired[float]


class Ref(TypedDict):
    kind: Literal["vertex"]
    index: int


class Ref1(TypedDict):
    kind: Literal["face"]
    side: Literal["min-x", "max-x", "min-y", "max-y"]


class Keystone(TypedDict):
    edge: Literal["left", "right", "top", "bottom"]
    ref: Ref | Ref1


class Piece(TypedDict):
    id: NotRequired[EntityId]
    name: NotRequired[str]
    piece_type: NotRequired[Literal["area", "feature"]]
    terrain: NotRequired[bool]
    template: NotRequired[EntityId]
    footprint: NotRequired[Footprint]
    position: Vec2
    rotation_degrees: NotRequired[float]
    mirror: NotRequired[Literal["none", "horizontal", "vertical"]]
    parent_area_id: NotRequired[EntityId]
    floor: NotRequired[int]
    height_inches: NotRequired[float]
    terrain_area_keywords: NotRequired[list[TerrainAreaKeyword]]
    link_group: NotRequired[str]
    objective_role: NotRequired[Literal["home", "expansion", "center"]]
    is_objective: NotRequired[bool]
    objective: NotRequired[Objective]
    keystones: NotRequired[list[Keystone]]


class Board(TypedDict):
    width: float
    height: float


class TerrainLayout(TypedDict):
    id: EntityId
    name: str
    source: NotRequired[str]
    description: NotRequired[str]
    mission_matchup_id: NotRequired[EntityId]
    variant: NotRequired[int]
    deployment_pattern_id: NotRequired[EntityId]
    board: NotRequired[Board]
    pieces: NotRequired[list[Piece]]
    game_version: GameVersionRef


class ComposedFeature(TypedDict):
    id: NotRequired[EntityId]
    template: EntityId
    position: Vec2
    rotation_degrees: NotRequired[float]
    mirror: NotRequired[Literal["none", "horizontal", "vertical"]]
    floor: NotRequired[int]


class UpperFloor(TypedDict):
    footprint: Footprint
    floor: NotRequired[int]


class TerrainTemplate(TypedDict):
    id: EntityId
    name: str
    kind: Literal["area", "feature"]
    source: NotRequired[str]
    footprint: Footprint
    default_height_inches: NotRequired[float]
    default_blocking: NotRequired[bool]
    ground_accessible: NotRequired[bool]
    upper_floor: NotRequired[UpperFloor]
    default_terrain_area_keywords: NotRequired[list[TerrainAreaKeyword]]
    features: NotRequired[list[ComposedFeature]]
    terrain_category: NotRequired[Literal["exposed", "light", "dense"]]
    walls: NotRequired[list[Wall]]
    has_roof: NotRequired[bool]
    outline: NotRequired[list[Vec2]]
    game_version: GameVersionRef


class LoadoutVariant(TypedDict):
    name: str
    weapon_ids: list[EntityId]
    max_count: NotRequired[int]


VariantName: TypeAlias = str


class LoadoutVariantBudget(TypedDict):
    variant_names: list[VariantName]
    count: int
    per_models: int
    scope: Literal["unit", "model-row"]


class Model(TypedDict):
    name: str
    profile_name: NotRequired[str | None]
    min: int
    max: int
    default_weapon_ids: NotRequired[list[EntityId]]
    is_leader_model: NotRequired[bool]
    base_size_mm: NotRequired[BaseSize]
    hull_shape_id: NotRequired[EntityId | None]
    loadout_variants: NotRequired[list[LoadoutVariant]]
    loadout_variant_budgets: NotRequired[list[LoadoutVariantBudget]]


class Model1(TypedDict):
    name: str
    min: int
    max: int


class Tier(TypedDict):
    models: list[Model1]


class UnitComposition(TypedDict):
    unit_id: EntityId
    faction_id: EntityId
    models: list[Model]
    tiers: NotRequired[list[Tier]]
    game_version: GameVersionRef
    game_modes: NotRequired[GameModes]


class OverridableParameter(TypedDict):
    name: str
    default: int | str
    unit: NotRequired[str]


class Profile(TypedDict):
    name: NotRequired[str]
    M: StatValue
    T: int
    W: int
    Sv: int
    invuln_sv: NotRequired[int | None]
    invuln_sv_ranged: NotRequired[int | None]
    invuln_sv_melee: NotRequired[int | None]
    Ld: int
    OC: int


class Point(TypedDict):
    models: int
    cost: int
    models_max: NotRequired[int]
    unit_count_min: NotRequired[int]
    unit_count_max: NotRequired[int | None]


class AlliedPoint(TypedDict):
    host_faction: EntityId
    models: int
    cost: int
    models_max: NotRequired[int]
    unit_count_min: NotRequired[int]
    unit_count_max: NotRequired[int | None]


class WargearCost(TypedDict):
    item_id: EntityId
    cost: int


class ConditionalKeyword(TypedDict):
    keyword: Keyword
    required_detachment_id: NotRequired[EntityId | None]
    required_faction_keyword: NotRequired[Keyword | None]


class ModelCount(TypedDict):
    min: int
    max: int


class WargearBudget(TypedDict):
    items: list[EntityId]
    count: int
    per_models: int
    duplicate_limit: NotRequired[int]


class TransportCapacity(TypedDict):
    capacity: int
    keyword_restrictions: NotRequired[KeywordList | None]
    exclusion_keywords: NotRequired[KeywordList | None]


class Unit(TypedDict):
    id: EntityId
    external_refs: NotRequired[ExternalReferenceList]
    name: str
    aliases: NotRequired[list[str]]
    faction_id: EntityId
    role: NotRequired[
        Literal[
            "character", "battleline", "dedicated-transport", "fortification", "allied", "epic-hero"
        ]
    ]
    attachment_role: NotRequired[Literal["leader", "support"] | None]
    profiles: list[Profile]
    points: NotRequired[list[Point]]
    allied_points: NotRequired[list[AlliedPoint]]
    points_provisional: NotRequired[bool]
    wargear_costs: NotRequired[list[WargearCost]]
    keywords: NotRequired[KeywordList]
    faction_keywords: NotRequired[KeywordList]
    conditional_keywords: NotRequired[list[ConditionalKeyword]]
    excluded_faction_keywords: NotRequired[KeywordList | None]
    base_size_mm: NotRequired[BaseSize | None]
    model_count: NotRequired[ModelCount]
    weapon_ids: NotRequired[list[EntityId]]
    ability_ids: NotRequired[list[EntityId]]
    wargear_budgets: NotRequired[list[WargearBudget]]
    transport_capacity: NotRequired[TransportCapacity | None]
    game_version: GameVersionRef
    is_legend: NotRequired[bool]
    game_modes: NotRequired[GameModes]


class ModelConstraint(TypedDict):
    model_name: NotRequired[str]
    per_n_models: NotRequired[int]
    max_count: NotRequired[int]
    any_number: NotRequired[bool]


ReplacementChoiceItem: TypeAlias = list[EntityId]


class WargearOption(TypedDict):
    id: EntityId
    unit_id: EntityId
    faction_id: EntityId
    model_constraint: NotRequired[ModelConstraint | None]
    replaces: NotRequired[list[EntityId]]
    replacement: NotRequired[list[EntityId]]
    replacement_choice: NotRequired[list[ReplacementChoiceItem]]
    is_free: NotRequired[bool]
    additional_cost: NotRequired[int | None]
    game_version: GameVersionRef
    game_modes: NotRequired[GameModes]


class Wargear(TypedDict):
    id: EntityId
    external_refs: NotRequired[ExternalReferenceList]
    name: str
    category: NotRequired[str | None]
    game_version: GameVersionRef


class Stats(TypedDict):
    A: StatValue
    BS: NotRequired[int | None]
    WS: NotRequired[int | None]
    S: StatValue
    AP: int
    D: StatValue


class Parameters(TypedDict):
    value: NotRequired[StatValue]
    target_keyword: NotRequired[str]
    threshold: NotRequired[int]
    required_target_keywords_any: NotRequired[list[Keyword]]
    excluded_target_keywords: NotRequired[KeywordList]


class Keyword1(TypedDict):
    keyword_id: EntityId
    parameters: NotRequired[Parameters]


class TargetRestrictions1(TypedDict):
    required_keywords_any: NotRequired[list[Keyword]]
    excluded_keywords: NotRequired[KeywordList]


class Profile1(TypedDict):
    name: str
    range: NotRequired[int | Literal["Melee"]]
    stats: Stats
    keywords: NotRequired[list[Keyword1]]
    target_restrictions: NotRequired[TargetRestrictions1 | None]


class Weapon(TypedDict):
    id: EntityId
    external_refs: NotRequired[ExternalReferenceList]
    name: str
    type: Literal["ranged", "melee"]
    faction_id: NotRequired[EntityId]
    profiles: list[Profile1]
    game_version: GameVersionRef
    game_modes: NotRequired[GameModes]


class CausedBy(TypedDict):
    source: Literal["bearer-model", "bearer-unit"]
    attack_type: NotRequired[Literal["melee", "ranged"]]
    weapon_keyword: NotRequired[str]


class Proximity(TypedDict):
    of: NotRequired[Literal["self", "bearer", "attached-unit", "bearer-unit"]]
    range: float


class Cost(TypedDict):
    cp: NotRequired[int]


Keyword2: TypeAlias = str


class SourceAbility(TypedDict):
    ability_id: EntityId
    owner: Literal["friendly", "enemy"]
    keywords: list[Keyword2]


SubjectKeyword: TypeAlias = str


SubjectExcludedKeyword: TypeAlias = str


class AbilityUsage(TypedDict):
    frequency: Literal[
        "once-per-turn",
        "once-per-phase",
        "once-per-battle-round",
        "once-per-command-phase",
        "once-per-opponent-turn",
        "n-per-battle",
        "first-this-battle",
        "first-time-this-phase",
    ]
    count: NotRequired[int]
    per: NotRequired[Literal["army", "unit", "model"]]


class AppliesTo(TypedDict):
    required_keywords: NotRequired[KeywordList]
    excluded_keywords: NotRequired[KeywordList]


class Interaction(TypedDict):
    ability_ref: EntityId
    type: Literal["conflicts-with", "combos-with", "superseded-by", "requires", "replaces"]
    notes: NotRequired[str]


class EventBoundReference(TypedDict):
    event_var: str


class SimpleCondition(TypedDict):
    type: Literal[
        "phase-is",
        "timing-is",
        "player-turn-is",
        "unit-below-starting-strength",
        "unit-below-half-strength",
        "unit-has-keyword",
        "unit-within-range-of",
        "model-is-leader",
        "target-has-keyword",
        "charged-this-turn",
        "advanced-this-turn",
        "remained-stationary",
        "is-battle-shocked",
        "has-lost-wounds",
        "wounds-remaining-at-or-below",
        "was-hit-by-attack",
        "wounds-lost-from-attack",
        "opponent-unit-within-range",
        "within-range-of-objective",
        "attack-is-type",
        "has-fought-this-phase",
        "destroyed-by-attack-type",
        "controls-objective",
        "is-attached",
        "terrain-area-control",
        "region-membership",
        "engagement-state",
        "territory-control",
        "fights-first",
        "disposition-matches",
        "units-destroyed",
        "units-destroyed-comparison",
        "objective-majority",
        "action-completed",
        "objective-has-tag",
        "unit-has-tag",
        "terrain-has-tag",
        "new-objective-controlled",
        "engagement-fronts",
        "destroyed-while-on-objective",
        "destroyed-in-tagged-terrain",
        "operation-markers",
        "attack-stat-compare",
        "made-ingress-move-this-turn",
        "disembarked-from-transport",
        "faction-rule-active",
        "battle-round",
        "token-count-at-or-above",
        "unit-was-in-engagement-range-of",
        "unit-model-count",
        "uniform-ranged-loadout",
        "all-attacks-target-same-unit",
        "target-is-visible",
        "ability-window-capacity",
        "candidate-eligible-in-ability-window",
        "unit-is-led-by",
        "on-battlefield",
        "target-within-half-weapon-range",
        "has-destroyed",
        "roll-succeeded",
        "unit-selected-to-shoot-this-phase",
        "eligible-to-shoot",
        "selection-has-keyword",
        "target-of-triggering-charge",
        "every-model-within-range-of-bearer",
        "event-source-is-bearer-unit",
        "event-source-is-attached-unit",
        "miracle-die-generation-reason",
        "miracle-die-generation-timing",
        "destroyed-event-within-range",
        "destroyed-by-friendly-unit",
    ]
    of: NotRequired[
        Literal["bearer", "unit", "led-unit", "attacker", "defender", "target", "friendly", "enemy"]
    ]
    parameters: NotRequired[dict[str, Any]]
    negated: NotRequired[bool]


GrantType: TypeAlias = Literal[
    "ability-range-modifier",
    "act-after-move",
    "act-after-shooting",
    "action-after-advance-fall-back",
    "action-after-fall-back",
    "action-and-shoot-eligibility",
    "action-eligibility",
    "action-eligibility-after-advance-or-fall-back",
    "activate-blessing-of-khorne",
    "activate-dread-ability",
    "add-embarked-oc-to-self-oc",
    "add-order",
    "additional-oath",
    "adjust-target-marker",
    "advance-6-instead-of-roll",
    "advance-and-charge",
    "advance-and-charge-if-selected-among-up-to-two-other-units",
    "advance-roll-set-to-six",
    "advance-through-all-models",
    "afflicted",
    "agile-manoeuvre-d6-add-1",
    "agile-manoeuvre-phase-limit-exemption",
    "all-blessings-of-khorne-active",
    "allied-astra-militarum-inclusion",
    "always-within-synapse-range",
    "apply-additional-plague",
    "apply-battle-shock",
    "army-composition-constraint",
    "army-list-allowance-one-inquisitorial-agents-unit-per-inquisitor",
    "army-list-allowance-one-voidsmen-at-arms-unit-per-voidfarers-character",
    "battle-focus",
    "battle-round-plus-one-for-arrival",
    "battle-shock-test",
    "battle-shock-test-re-roll",
    "battle-shocked-status",
    "battle-shocked-targeting-permission",
    "becomes-battle-shocked",
    "benefit-of-cover-against-triggering-attack",
    "blessings-of-khorne",
    "bodyguard-sacrifice-psychic-buff",
    "bomb-squig-first-sub-unit-found-em-second-sub-unit",
    "bondsman-select-three-armiger-12in",
    "bondsman-select-three-armiger-15in",
    "bonus-healing-d3",
    "boon-of-blood",
    "boost-psychic-test-via-mortal-wounds",
    "butcha-boyz-embarked-model-attack-scaling-2-cap-22",
    "cabal-of-sorcerers",
    "cannot-be-targeted-by-fire-overwatch",
    "cannot-be-warlord",
    "cannot-benefit-from-cover",
    "cannot-charge-this-turn",
    "cannot-embark-transport",
    "cannot-embark-venerable-land-raider",
    "cannot-have-benefit-of-cover",
    "cannot-use-personal-teleporters",
    "canticle",
    "charge-after-advance",
    "charge-after-advance-fallback",
    "charge-after-advance-or-fall-back",
    "charge-after-advance-or-fallback",
    "charge-after-disembark",
    "charge-after-fall-back",
    "charge-after-fallback",
    "charge-after-movement",
    "charge-eligibility-after-advance-or-fall-back",
    "charge-eligible-after-normal-move-disembark",
    "charge-ineligible",
    "charge-ineligible-for-remainder-of-turn",
    "choice",
    "contagion-range-extension-3",
    "contagion-range-modifier",
    "corsair-enhancement-selection",
    "counts-as-advanced-this-turn",
    "covered-in-squigs",
    "create-identical-replacement-unit",
    "crew-tokens",
    "critical-hit-on",
    "critical-wound-on-successful-wound-roll",
    "daemon-primarch-of-slaanesh-selection",
    "daemonic-rage",
    "dark-pact-both-abilities",
    "dark-pacts",
    "deadly-demise-choose-result",
    "deadly-demise-d6",
    "deadly-demise-disabled",
    "deadly-demise-threshold",
    "declare-charge",
    "deep-strike",
    "deep-strike-6",
    "deep-strike-6inch-exclusion",
    "deep-strike-for-selected-kroot-units",
    "deep-strike-within-flow-of-magic",
    "defence-line-section-assembly",
    "deferred-destroyed-model-removal",
    "deferred-removal-until-fought-or-end-of-phase",
    "delayed-model-removal",
    "deny-reinforcements-within-12",
    "designate-enemy-detection-range-modifier",
    "designate-target-marker",
    "designated-objective-oc-bonus",
    "desperate-escape",
    "desperate-escape-hazard-minus-one",
    "desperate-escape-tests-on-fall-back",
    "detachment-enhancements-gain-expended-state",
    "detachment-saga-completed",
    "detection-range-extended-6",
    "detection-range-minus-3-inches",
    "detection-range-modifier",
    "disembark-after-advance-charge",
    "disembarking-pulse-weapons-attack-bonus",
    "eadbanger-ranged-weapon-range-24in-bs-4plus",
    "eligible-to-declare-charge-after-fall-back",
    "eligible-to-fight-again",
    "eligible-to-start-action-after-advance-or-fall-back",
    "eligible-to-start-an-action-after-an-advance-move",
    "embark-after-enemy-shooting",
    "embark-after-fight",
    "embark-at-end-of-fight-phase",
    "embark-in-selected-transport",
    "embark-in-transport",
    "embark-when-charged",
    "empower-possessed-blade",
    "enable-rapid-disembark-for-embarked-units",
    "engaged-enemies-must-prefer-scintillating-legions-targets",
    "engaged-enemies-must-target-this-unit",
    "enhanced-foul-spores-aura-9",
    "enraged-abjuration",
    "enter-strategic-reserves",
    "expended-enhancement-cannot-be-used",
    "expended-enhancements-all-refreshed",
    "extend-bondsman-range",
    "extend-datasheet-aura-range",
    "extend-psychic-ability-range-6",
    "extend-ritual-range-6",
    "extended-fight-eligibility",
    "extended-order-range",
    "extra-leader-attachment",
    "extra-order",
    "extra-ritual-attempt",
    "extremis-double-ability-uses",
    "fade-back-agile-manoeuvre-free",
    "fallback-denial-on-leadership-failure",
    "fallback-exception",
    "fallback-hazard-auto-pass",
    "farsight-ethereal-mutual-exclusion",
    "fight-one-additional-time",
    "fire-overwatch-targeting-immunity",
    "flexible-strategic-reserves",
    "forced-battle-shock-roll",
    "forced-battle-shock-test",
    "found-em-first-sub-unit-bomb-squig-second-sub-unit",
    "free-tank-shock",
    "grenade-stratagem-free-use",
    "guided-units-lethal-hits-vs-spotted",
    "guided-units-sustained-hits-1-vs-spotted",
    "half-range-consideration",
    "harnessed-alien-instincts",
    "hazard-check-pair-per-selected-tagged-weapon",
    "hazard-roll-per-model",
    "heal-bonus",
    "heal-d3-wounds",
    "heal-wounds",
    "hero-of-hades-hive-ability",
    "heroic-intervention-at-0cp",
    "heroic-intervention-frequency-bypass",
    "heroic-intervention-limit-exempt",
    "icon-of-war-selection",
    "idol-of-blessed-blood",
    "idol-of-burning-wrath",
    "idol-of-infinite-rage",
    "ignore-hit-roll-modifiers",
    "ignore-move-and-advance-modifiers",
    "ignore-strategic-reserves-unit-cap",
    "improved-grenades-mortal-wound-threshold",
    "incoming-psychic-attacks-hazardous",
    "incoming-ranged-attacks-ignore-cover-through-end-of-next-friendly-turn",
    "incoming-unmodified-ranged-hit-results-one-through-three-fail",
    "increased-detection-range",
    "individual-model-deployment-within-12-coherency",
    "infiltrators",
    "infiltrators-for-selected-rubricae",
    "ingress-into-enemy-deployment-zone",
    "ingress-move",
    "ingress-within-6",
    "intervening-line-of-sight-cover",
    "into-strategic-reserves",
    "issue-extra-order-to-abhuman-unit",
    "issue-order-to-disembarked-regiment-unit",
    "issue-order-to-extra-platoon-units",
    "issue-order-to-multiple-units",
    "issue-orders",
    "issue-orders-regiment-up-to-2",
    "killing-blow-extended-round-4",
    "kindred-sorcery-choice-override",
    "leader-attachment",
    "leadership-test-or-3-mortal-wounds",
    "leadership-test-re-roll",
    "localised-stealth-projectors",
    "lone-operative",
    "lose-infantry-keyword",
    "make-a-blessings-of-khorne-roll-and-activate-one-additional-blessing",
    "make-one-hazard-roll",
    "mandatory-desperate-escape",
    "mandatory-warlord-designation",
    "may-start-in-reserves",
    "melee-cleave-increment-if-present",
    "melee-cleave-one-if-absent",
    "melee-critical-hit-on-5-plus",
    "melta-range-add-6",
    "might-of-khorne",
    "miracle-dice-reroll-before-pool",
    "miracle-dice-value-set-6",
    "mobbed-roll-adjustment-plus-one-or-minus-two-at-three-models",
    "mobile",
    "model-passthrough-excluding-monsters-and-vehicles",
    "models-within-3-are-eligible-to-fight-and-can-target-enemy-units-within-3",
    "move-does-not-prevent-action",
    "move-must-finish-in-objective-range",
    "move-through-models",
    "multi-target-attack",
    "multiple-orders",
    "multiple-orders-up-to-two",
    "must-be-warlord",
    "must-start-in-reserves",
    "mutated-objective-hazard",
    "no-advance-roll",
    "no-smoke",
    "normal-move-d3-plus-3-inches",
    "nurgle-gift",
    "nurgle-gift-as-death-guard-model",
    "oath-fulfilled",
    "optional-redeployment-selection",
    "optional-restore-three-lost-wounds",
    "orders-persist-during-battle-shock",
    "outflank-set-up-in-opponent-deployment-zone",
    "pact-both-abilities",
    "passenger-relocation-on-destruction",
    "patient-hunter-from-round-2",
    "perform-ingress-move",
    "perform-pulse-jet-move",
    "permit-embarked-units-assault-disembark",
    "persistent-orders",
    "pinned",
    "place-in-strategic-reserves",
    "place-into-strategic-reserves",
    "place-replacement-in-strategic-reserves",
    "place-selected-unit-in-strategic-reserves",
    "plague-selection",
    "platform-setup-and-move-override",
    "post-deployment-redeploy",
    "post-fallback-actions",
    "pregame-redeploy-up-to-three-infantry-units",
    "pregame-redeploy-up-to-three-infantry-units-may-enter-strategic-reserves",
    "pregame-redeploy-up-to-three-units-may-enter-strategic-reserves",
    "pregame-redeploy-up-to-two-regiment-or-squadron-units-may-enter-strategic-reserves",
    "primarch-of-the-first-legion-selection",
    "psychic-abilities",
    "psychic-abilities-level-one",
    "psychic-level-1",
    "psychic-level-2",
    "ranged-rapid-fire-floor-one-increment-existing",
    "ranged-weapon",
    "ranged-weapon-range-plus-3in",
    "ranged-weapon-range-plus-three-excluding-torrent",
    "re-roll-advance",
    "re-roll-channelling-die-at-vehicle-wound-cost",
    "re-roll-hazardous-tests-psychic",
    "re-roll-psychic-rolls",
    "reactive-charge",
    "reactive-embark-when-charged",
    "redeploy-heretic-astartes-to-reserves",
    "redeploy-on-battlefield",
    "redeploy-to-reserves",
    "redeploy-to-strategic-reserves",
    "redeploy-up-to-3-astra-militarum-to-strategic-reserves-override",
    "redeploy-up-to-three-friendly-orks-infantry",
    "redeployment-selection-cap-three",
    "reinforcement-any-of-turns-1-to-3",
    "reinforcements-first-three-movement-phases",
    "relics-of-matriarchs",
    "remain-hidden-after-shooting",
    "remove-already-destroyed-model-from-battlefield",
    "remove-battle-shock",
    "remove-battle-shocked-status",
    "remove-from-battlefield-after-resolution",
    "remove-hunter-organism",
    "replace-destroyed-unit-in-reserves",
    "replace-melee-attack-bonus-with-plus-two-at-eleven-models",
    "reroll-advance",
    "reroll-duplicate-random-results",
    "reserve-deployment-denial-aura-12",
    "reserves-limit-exempt",
    "reserves-limit-exempt-with-cargo",
    "restore-replacement-to-original-model-count-and-full-health",
    "restricted-from-warlord",
    "return-destroyed-models",
    "reuse-once-per-battle-ability",
    "riled-up-expiring-at-next-friendly-turn-boundary",
    "ritual-bonus-on-cabal-death",
    "roll-off-winner-chooses-redeploy-order",
    "same-unit-surge-move-up-to-d6",
    "scornful-analysis-designated",
    "scouts-6",
    "scouts-7",
    "scouts-9-transport",
    "select-doombolt-ignoring-attempt-limit",
    "select-new-quarry",
    "select-one-infantry-unit-gains-scouts-6",
    "select-up-to-two-ctan-powers-restrict-others",
    "selected-embarked-orks-infantry-disembark-move",
    "selective-from-pool",
    "set-up-as-close-as-possible-to-destroyed-location-unengaged",
    "shadow-form-ability-select",
    "shadow-of-chaos",
    "shaken-status",
    "share-war-dog-auras",
    "shoot-after-action",
    "shoot-after-advance",
    "shoot-after-advance-or-fall-back",
    "shoot-after-fall-back",
    "shoot-after-fallback",
    "shoot-again",
    "shoot-and-charge-after-advance-fall-back",
    "shoot-and-charge-after-fall-back",
    "shoot-as-if-shooting-phase",
    "shoot-out-of-phase",
    "shoot-while-hidden",
    "shoot-while-in-action",
    "shoot-while-performing-action",
    "shooting-does-not-prevent-hidden",
    "snap-shooting",
    "snap-shooting-response",
    "split-by-headtakers-hunting-wolves",
    "split-into-single-model-units",
    "split-unit-five-five",
    "spotted",
    "stand-on-terrain-sections",
    "stealth",
    "stratagem-cost-reduction",
    "stratagem-for-0cp",
    "stratagem-targetable-while-battle-shocked",
    "strategic-reserves-during-redeployment",
    "strategic-reserves-exempt",
    "strategic-reserves-override",
    "strategic-reserves-without-unit-limit",
    "summon-chaos-spawn-on-death",
    "summon-poxwalkers-strategic-reserves",
    "super-heavy-walker",
    "suppress-shot-target-hit-penalty",
    "suppressed",
    "surrogate-hosts",
    "swap-hostile-acquisition-and-fortify-takeover",
    "take-battle-shock-test",
    "take-to-the-skies",
    "tank-shock-zero-cp-unrestricted",
    "targetable-by-ranged-while-engaged",
    "temple-relics",
    "terminate-current-attack-sequence",
    "terror-of-khorne",
    "titanic-self-aura-inclusion",
    "transport-capacity-30-with-keyword-multipliers",
    "treat-battle-round-one-higher-for-reserves",
    "treat-roll-as-unmodified-6",
    "tunnel-marker-reserves-deployment",
    "unhideable-through-end-of-next-friendly-turn",
    "unmodified-hit-critical",
    "use-the-blue-horrors-datasheet",
    "vanguard-selection",
    "vengeance-move",
    "vow-of-atonement-selection",
    "warlord",
    "warmaster-selection",
    "weapon",
    "weapon-grant",
    "weapon-range-increase",
    "wholly-within-flow-of-magic",
    "withdraw-to-strategic-reserves",
    "wrathful-presence-selection",
]


class Scaling(TypedDict):
    per: int
    of: Literal[
        "enemy-models-in-range",
        "friendly-models-in-range",
        "models-in-bearer-unit",
        "models-in-or-embarked-in-bearer",
        "enemy-units-in-range",
        "wounds-lost",
    ]
    within_inches: NotRequired[float]
    round: NotRequired[Literal["down", "up"]]
    max_value: NotRequired[int]


RuleStateCoreRuleSlug: TypeAlias = Literal[
    "benefit-of-cover",
    "fall-back",
    "ordered-retreat",
    "advance",
    "charge",
    "fire-overwatch",
    "overwatch-against-bearer",
    "desperate-escape",
]


class DiceRequirement(TypedDict):
    type: Literal["pair", "triple", "single", "run"]
    min_value: int


class DiceRequirementSpec1(TypedDict):
    any_of: list[DiceRequirement]


DiceRequirementSpec: TypeAlias = DiceRequirement | DiceRequirementSpec1


class SingleEffect(TypedDict):
    type: Literal[
        "ability-grant",
        "attack-restriction",
        "auto-result",
        "battle-shock-test",
        "bs-modifier",
        "charge-roll-modifier",
        "cp-gain",
        "cp-on-destroy",
        "cp-refund",
        "damage-reduction",
        "deep-strike",
        "disembark",
        "disembark-after-move",
        "engagement-passthrough",
        "fallback-and-act",
        "feel-no-pain",
        "fight-eligibility-extension",
        "fight-first",
        "fight-last",
        "fight-on-death",
        "firing-deck",
        "flyover",
        "heal-wounds",
        "hazard-rolls",
        "invulnerable-save",
        "keyword-grant",
        "leadership-modifier",
        "model-destruction",
        "modifier-immunity",
        "mortal-wounds",
        "detection-range-modifier",
        "named-region-state",
        "objective-control-modifier",
        "objective-tag",
        "pool-add-die",
        "re-roll",
        "recovery-pool",
        "remove-battle-shock",
        "set-battle-shock",
        "replace-roll-from-pool",
        "resource-clear",
        "resource-gain",
        "resource-spend",
        "resurrection",
        "roll-modifier",
        "rule-state",
        "shoot-on-death",
        "stat-modifier",
        "stratagem-cost-modifier",
        "stratagem-targeting-permission",
        "strategic-reserves-arrival",
        "targeting-permission",
        "tracking-token",
        "transport-capacity-conversion",
        "terrain-area-tag",
        "unit-attachment",
        "unit-keyword",
        "unit-keyword-grant",
        "unit-tag",
        "ward",
        "unit-division",
        "desperate-escape",
        "reactive-charge",
        "ability-usage-limit",
        "deadly-demise-threshold",
        "embark",
    ]
    target: Literal[
        "self",
        "bearer",
        "unit",
        "attached-unit",
        "selected-models-unit",
        "attacker",
        "defender",
        "target",
        "targets-of-selected-unit-attacks",
        "friendly-within-aura",
        "enemy-within-aura",
        "all-friendly",
        "all-enemy",
        "destroyed-model",
        "triggering-unit",
    ]
    modifier: NotRequired[dict[str, Any]]
    scaling: NotRequired[Scaling]


Result: TypeAlias = int


class Pool(TypedDict):
    count: int
    die: str


class SelectionLimit(TypedDict):
    count: int
    period: Literal["turn", "phase", "battle-round", "battle"]


ModelName: TypeAlias = str


ExcludedKeyword: TypeAlias = str


class Marker(TypedDict):
    affected: NotRequired[str]
    unit_filter: NotRequired[str]
    location: NotRequired[str]
    max_units: NotRequired[int]


RangeItem: TypeAlias = int


RequiredKeyword: TypeAlias = str


class Eligible(TypedDict):
    required_keywords: NotRequired[list[RequiredKeyword]]
    excluded_keywords: NotRequired[list[ExcludedKeyword]]


class SelectionLimit2(TypedDict):
    count: int
    period: Literal["phase", "turn", "battle-round", "battle"]


AttackerKeyword: TypeAlias = str


AttackerUnitKeyword: TypeAlias = str


class Eligible1(TypedDict):
    keyword: NotRequired[str]


TransportOccupancySubjectKind: TypeAlias = Literal["unit-models", "single-model"]


class TransportEligibility1(TypedDict):
    requires_capacity_keyword: str
    embark_as_keyword: NotRequired[str]


class TransportEligibility2(TypedDict):
    requires_capacity_keyword: NotRequired[str]
    embark_as_keyword: str


TransportEligibility: TypeAlias = TransportEligibility1 | TransportEligibility2


ResourceGainBattleSizeCounts = TypedDict(
    "ResourceGainBattleSizeCounts",
    {
        "incursion": int,
        "strike-force": int,
        "onslaught": int,
    },
)


class SharedUsage(TypedDict):
    unit_max_manoeuvres_per_phase: NotRequired[int]
    default_manoeuvre_max_per_phase: NotRequired[int]


class Cost1(TypedDict):
    pool_id: str
    amount: int
    resource_label: NotRequired[str]


class Usage(TypedDict):
    repeatable_if_different_unit: NotRequired[bool]


class Proximity1(TypedDict):
    of: NotRequired[Literal["self", "bearer", "attached-unit"]]
    range: float


class Cost2(TypedDict):
    cp: NotRequired[int]


class NamedRegionRef(TypedDict):
    region_id: str
    owner_faction: str


class UnitPredicate(TypedDict):
    faction: str
    keywords: list[Keyword2]


class NamedRegionSourceGate(TypedDict):
    gate_ref: str
    owner: str
    unit_predicate: UnitPredicate
    range_to_marker_inches: NotRequired[float]


class NamedRegionMembership(TypedDict):
    unit_scope: Literal["model", "whole-unit"]
    relation: str


class NamedRegionBranchActor(TypedDict):
    role: str
    gate_ref: str


class NamedRegionBranchTiming(TypedDict):
    event: str


class Activation(TypedDict):
    event: Literal["always-active"]


class Expiry(TypedDict):
    event: Literal["never"]


class NamedRegionBaseline(TypedDict):
    kind: Literal["fixed-zone"]
    zone: Literal["own-deployment-zone"]
    activation: Activation
    expiry: Expiry


class Threshold(TypedDict):
    comparison: Literal["at-least"]
    fraction: float


class ControlGate(TypedDict):
    marker_scope: Literal["markers-in-zone"]
    controlled_by: Literal["owner-army"]
    threshold: Threshold


class Activation1(TypedDict):
    event: Literal["phase-start"]
    evaluation: Literal["snapshot-once"]
    canonical_condition_ids: list[str]


class Expiry1(TypedDict):
    event: Literal["phase-end"]


class NamedRegionPhaseExtension(TypedDict):
    kind: Literal["objective-majority-zone"]
    zone: Literal["no-mans-land", "opponent-deployment-zone"]
    control_gate: ControlGate
    activation: Activation1
    expiry: Expiry1


class Activation2(TypedDict):
    event: Literal["continuous"]


class AdditiveExtension(TypedDict):
    kind: str
    source_gate: NamedRegionSourceGate
    radius_inches: NotRequired[float]
    activation: NotRequired[Activation2]


class NamedRegionProducer(TypedDict):
    region_ref: NamedRegionRef
    mode: Literal["complete", "extension"]
    parent_ref: NamedRegionRef | None
    baseline: list[NamedRegionBaseline]
    phase_extensions: list[NamedRegionPhaseExtension]
    additive_extensions: list[AdditiveExtension]


class BeneficiaryGate(TypedDict):
    owner: str
    faction: NotRequired[str]
    operator: Literal["and", "or"]
    keywords: list[Keyword2]


class KeywordFilter(TypedDict):
    required_keywords: list[RequiredKeyword]
    excluded_keywords: NotRequired[list[ExcludedKeyword]]


class BeneficiaryBoundEffectNode(TypedDict):
    type: str
    modifier: NotRequired[dict[str, Any]]
    scaling: NotRequired[Scaling]


class LeaderFilter(TypedDict):
    identity: NotRequired[str]
    keywords: NotRequired[list[Keyword2]]


AttachedUnitFilterItem: TypeAlias = str


class Grant(TypedDict):
    recipient: Literal["beneficiary"]
    effect: BeneficiaryBoundEffectNode


class LeaderModelAbilityGrantEffect(TypedDict):
    type: Literal["leader-model-ability-grant"]
    source: Literal["bearer-unit"]
    beneficiary: Literal["leading-leader-model", "attached-character-leader"]
    leader_filter: NotRequired[LeaderFilter]
    attached_unit_filter: list[AttachedUnitFilterItem] | None
    duration: Literal["while-leading"]
    grant: Grant
    recipient_binding: Literal["beneficiary-only"]


class Select1(TypedDict):
    scope: Literal["enemy-unit", "objective-marker"]
    count: NotRequired[Literal[1]]
    timing: str
    selection_policy: Literal["one-time", "replace-on-destroyed"]
    allow_while_embarked: NotRequired[bool]
    bind_as: NotRequired[str]


class NoEffectEffect(TypedDict):
    type: Literal["no-effect"]


class SelectionReference(TypedDict):
    selection_var: str


EventOrSelectionReference: TypeAlias = EventBoundReference | SelectionReference


class RequiresUnit(TypedDict):
    owner: Literal["friendly", "enemy"]
    requires_ability: str
    relation: Literal["within-range"]


class SelectionLimit3(TypedDict):
    count: int
    period: Literal["turn", "phase", "battle-round", "battle"]


class ObjectiveSelector(TypedDict):
    count: Literal[1]
    range_inches: NotRequired[float]
    origin: NotRequired[Literal["bearer", "bearer-unit"]]
    controlled_by: NotRequired[Literal["your-army", "opponent"]]
    requires_unit: NotRequired[RequiresUnit]
    selection_limit: NotRequired[SelectionLimit3]
    bind_as: str


class Selector31(TypedDict):
    owner: Literal["friendly", "enemy"]
    count: Literal[1]
    selection_mode: NotRequired[Literal["any-number"]]
    requires_ability: NotRequired[str]
    visible_to: NotRequired[SelectionReference]
    selection_limit: NotRequired[SelectionLimit3]
    bind_as: str


class Selector32(TypedDict):
    owner: Literal["friendly", "enemy"]
    count: NotRequired[Literal[1]]
    selection_mode: Literal["any-number"]
    requires_ability: NotRequired[str]
    visible_to: NotRequired[SelectionReference]
    selection_limit: NotRequired[SelectionLimit3]
    bind_as: str


class Selector33(TypedDict):
    owner: NotRequired[Literal["friendly"]]
    selection_mode: Literal["any-number"]
    requires_ability: Any


class Selector34(Selector31, Selector33):
    pass


class Selector35(Selector32, Selector33):
    pass


Selector3: TypeAlias = Selector34 | Selector35


class Observer(TypedDict):
    role: Literal["observer"]
    selector: Selector3


class Selector41(TypedDict):
    owner: Literal["friendly", "enemy"]
    count: Literal[1]
    selection_mode: NotRequired[Literal["any-number"]]
    requires_ability: NotRequired[str]
    visible_to: NotRequired[SelectionReference]
    selection_limit: NotRequired[SelectionLimit3]
    bind_as: str


class Selector42(TypedDict):
    owner: Literal["friendly", "enemy"]
    count: NotRequired[Literal[1]]
    selection_mode: Literal["any-number"]
    requires_ability: NotRequired[str]
    visible_to: NotRequired[SelectionReference]
    selection_limit: NotRequired[SelectionLimit3]
    bind_as: str


class Selector43(TypedDict):
    owner: NotRequired[Literal["enemy"]]
    count: Literal[1]
    visible_to: Any
    selection_limit: Any


class Selector44(Selector41, Selector43):
    pass


class Selector45(Selector42, Selector43):
    pass


Selector4: TypeAlias = Selector44 | Selector45


class Spotted(TypedDict):
    role: Literal["spotted"]
    selector: Selector4


class Guided(TypedDict):
    role: Literal["guided"]
    owner: Literal["friendly"]
    requires_ability: str
    excludes: SelectionReference
    while_attacking: SelectionReference


class PairedUnitSelector1(TypedDict):
    owner: Literal["friendly", "enemy"]
    count: Literal[1]
    selection_mode: NotRequired[Literal["any-number"]]
    requires_ability: NotRequired[str]
    visible_to: NotRequired[SelectionReference]
    selection_limit: NotRequired[SelectionLimit3]
    bind_as: str


class PairedUnitSelector2(TypedDict):
    owner: Literal["friendly", "enemy"]
    count: NotRequired[Literal[1]]
    selection_mode: Literal["any-number"]
    requires_ability: NotRequired[str]
    visible_to: NotRequired[SelectionReference]
    selection_limit: NotRequired[SelectionLimit3]
    bind_as: str


PairedUnitSelector: TypeAlias = PairedUnitSelector1 | PairedUnitSelector2


class RollReference(TypedDict):
    roll_var: str


class MiracleDieReference(TypedDict):
    die_var: str


class Count(TypedDict):
    minimum: Literal[1]
    maximum: Literal[1, 3]


Selection = TypedDict(
    "Selection",
    {
        "count": Literal[1] | Count,
        "from": Literal["dice-used-in-triggering-act-of-faith", "retained-pool-dice"],
        "policy": Literal["controller-chooses"],
    },
)


class Modifier3(TypedDict):
    operation: Literal[
        "reroll-generated-result",
        "set-generated-value-without-roll",
        "set-used-value",
        "reroll-retained-and-return",
    ]
    die: NotRequired[MiracleDieReference]
    value: NotRequired[int]
    pool_id: Literal["miracle-dice-pool"]
    resource_label: Literal["Miracle dice"]
    stage: NotRequired[Literal["before-pool-add", "before-act-of-faith-resolution"]]
    selection: NotRequired[Selection]
    optional: NotRequired[bool]


class MiracleDieOperationEffect(TypedDict):
    type: Literal["miracle-die-operation"]
    target: Literal["self"]
    modifier: Modifier3


class Attachment(TypedDict):
    leader_id: NotRequired[EntityId]
    bodyguard_id: EntityId


class FormationAttachmentGrantEffect(TypedDict):
    type: Literal["formation-attachment-grant"]
    source: Literal["self", "bearer-unit"]
    beneficiary: Literal["self", "attached-leader-model"]
    formation_event: Literal["declare-battle-formations"]
    attachment: Attachment
    grant: Grant


class Modifier4(TypedDict):
    leader_id: EntityId
    required_leader_ability: Literal["Leader"]
    from_bodyguard_id: EntityId
    to_bodyguard_id: EntityId


class AttachmentEligibilityInheritEffect(TypedDict):
    type: Literal["attachment-eligibility-inherit"]
    target: Literal["self"]
    modifier: Modifier4


ScopeDuration: TypeAlias = Literal[
    "phase",
    "turn",
    "battle-round",
    "battle",
    "until-next-command-phase",
    "until-next-movement-phase",
    "until-next-battle-round",
    "until-start-next-turn",
    "one-use",
    "permanent",
    "attack-sequence",
    "resolution",
]


class Scope(TypedDict):
    range: Literal[
        "self",
        "unit",
        "attached",
        "aura-6",
        "aura-9",
        "aura-12",
        "aura-custom",
        "engagement-range",
        "any-visible",
        "any-on-battlefield",
        "terrain-within-range",
    ]
    duration: ScopeDuration
    range_inches: NotRequired[float]


class InteractionFlag(TypedDict):
    ability_a: EntityId
    ability_b: EntityId
    interaction_type: Literal[
        "conflicts", "combos", "sequencing-dependent", "stacks", "does-not-stack", "replaces"
    ]
    resolution: NotRequired[str]
    faq_reference: NotRequired[str]
    disputed: NotRequired[bool]
    game_version: GameVersionRef
    authored_by: NotRequired[ContributorRef]


class PhaseMapping(TypedDict):
    source_id: EntityId
    source_type: SourceType
    phases: PhaseList
    game_version: GameVersionRef
    authored_by: NotRequired[ContributorRef]


class Replace(TypedDict):
    event: Literal["on-unit-destroyed"]
    reference: SelectionReference
    optional: bool


class Lifecycle(TypedDict):
    replace: Replace
    exclusivity: Literal["one-active-per-bearer-unit"]
    expiry: Literal["battle-end"]


class Action(TypedDict):
    action_id: NotRequired[str]
    starts: NotRequired[Phase]
    timing: NotRequired[Literal["start-of-battle", "start-of-turn", "end-of-turn"]]
    battle_round: NotRequired[BattleRound]
    player_turn: NotRequired[PlayerTurn]
    units: NotRequired[Condition]
    use_limit: NotRequired[int]
    use_limit_scope: NotRequired[Literal["per-turn", "per-game"]]
    completes: NotRequired[Condition]
    effect: NotRequired[Effect]
    restrictions: NotRequired[Condition]


class Awards(TypedDict):
    trigger: ScoringTrigger
    when: NotRequired[Condition]
    vp: int
    vp_per: NotRequired[int]
    per: NotRequired[str]
    per_max: NotRequired[int]
    vp_max: NotRequired[int]
    mode: NotRequired[Literal["fixed", "tactical"]]
    cumulative: NotRequired[bool]
    exclusive_group: NotRequired[str]


class Awards1(TypedDict):
    trigger: ScoringTrigger
    when: NotRequired[Condition]
    vp: NotRequired[int]
    vp_per: int
    per: str
    per_max: NotRequired[int]
    vp_max: NotRequired[int]
    mode: NotRequired[Literal["fixed", "tactical"]]
    cumulative: NotRequired[bool]
    exclusive_group: NotRequired[str]


class SecondaryCard(TypedDict):
    id: EntityId
    name: str
    card_type: NotRequired[Literal["secondary", "primary"]]
    subtype: NotRequired[str]
    when_drawn: NotRequired[WhenDrawn]
    actions: NotRequired[list[Action]]
    awards: NotRequired[list[Awards | Awards1]]
    text: NotRequired[str]
    game_version: GameVersionRef


class UnitKeyword(TypedDict):
    id: EntityId
    name: str
    required_parameters: list[Literal["value"]]
    overridable_parameters: NotRequired[list[OverridableParameter]]
    effect: Effect | None
    game_version: GameVersionRef


class WeaponKeyword(TypedDict):
    id: EntityId
    name: str
    required_parameters: list[Literal["value", "target_keyword", "threshold"]]
    effect: Effect | None
    game_version: GameVersionRef


class Trigger(TypedDict):
    event: GameEvent
    subject: NotRequired[
        Literal[
            "self",
            "bearer",
            "friendly-unit",
            "enemy-unit",
            "any-unit",
            "model-in-bearer",
            "friendly-model",
            "enemy-model",
        ]
    ]
    caused_by: NotRequired[CausedBy]
    proximity: NotRequired[Proximity]
    move_types: NotRequired[list[Literal["normal", "advance", "fall-back", "charge"]]]
    condition: NotRequired[Condition]
    optional: NotRequired[bool]
    cost: NotRequired[Cost]
    window: NotRequired[str]
    binds_event_variable: NotRequired[str]
    source_ability: NotRequired[SourceAbility]
    subject_keywords: NotRequired[list[SubjectKeyword]]
    subject_excluded_keywords: NotRequired[list[SubjectExcludedKeyword]]
    binds_die_variable: NotRequired[str]
    binds_selected_die_variable: NotRequired[str]


AbilityTrigger: TypeAlias = Trigger | list[Trigger]


class Ability(TypedDict):
    ability_id: EntityId
    name: str
    authored_by: ContributorRef
    game_version: GameVersionRef
    source_digest: NotRequired[str]
    version: NotRequired[DataslateVersion]
    supersedes: NotRequired[DataslateVersion | None]
    unit_ids: NotRequired[list[EntityId]]
    faction_id: NotRequired[EntityId | None]
    detachment_id: NotRequired[EntityId | None]
    ability_type: NotRequired[
        Literal["core", "faction", "detachment", "unit", "enhancement", "stratagem"]
    ]
    behavior: NotRequired[Literal["passive", "activated", "reactive", "aura"]]
    effect: Effect
    trigger: NotRequired[AbilityTrigger]
    scope: Scope
    usage: NotRequired[AbilityUsage]
    applies_to: NotRequired[AppliesTo | None]
    interactions: NotRequired[list[Interaction]]
    disputed: NotRequired[bool]
    dispute_notes: NotRequired[str]
    community_notes: NotRequired[str]


ConditionNode: TypeAlias = Union[SimpleCondition, "CompoundCondition"]


class CompoundCondition(TypedDict):
    operator: Literal["and", "or", "not"]
    operands: list[ConditionNode]


Condition: TypeAlias = ConditionNode


EffectNode: TypeAlias = Union[
    SingleEffect,
    "StanceSelectEffect",
    "ChoiceEffect",
    "SequenceEffect",
    "RulesBundleEffect",
    "NamedEffect",
    "DiceGatedEffect",
    "DiceTableEffect",
    "ConditionalEffect",
    "DicePoolAllocationEffect",
    "SelectUnitsEffect",
    "ForEachUnitEffect",
    "MovementModifierEffect",
    "AuraEffect",
    "DesignateTargetEffect",
    "RiskRewardEffect",
    "IssueOrdersEffect",
    "ResourceActionMenuEffect",
    LeaderModelAbilityGrantEffect,
    "PersistentDesignationEffect",
    NoEffectEffect,
    "SelectObjectiveEffect",
    "ForEachObjectiveEffect",
    "PairedDesignationEffect",
    MiracleDieOperationEffect,
    FormationAttachmentGrantEffect,
    AttachmentEligibilityInheritEffect,
]


class ChoiceEffect(TypedDict):
    type: Literal["choice"]
    options: list[EffectNode]
    choice_label: NotRequired[str]
    choice_prompt: NotRequired[str]
    min_choices: NotRequired[int]
    max_choices: NotRequired[int]


class SequenceEffect(TypedDict):
    type: Literal["sequence"]
    steps: list[EffectNode]


class RulesBundleEffect(TypedDict):
    type: Literal["rules-bundle"]
    steps: list[EffectNode]


class NamedEffect(TypedDict):
    type: Literal["named-effect"]
    name: str
    kind: NotRequired[Literal["psychic"]]
    level: NotRequired[int]
    effect: EffectNode
    optional: NotRequired[bool]
    cost: NotRequired[EffectNode]
    duration: NotRequired[ScopeDuration]
    trigger: NotRequired[AbilityTrigger]
    usage: NotRequired[AbilityUsage]


class Modifier(TypedDict):
    condition: Condition
    value: int


class Test(TypedDict):
    kind: Literal["leadership", "battle-shock"]
    subject: Literal["unit", "self", "target"]
    modifiers: NotRequired[list[Modifier]]


class DiceGatedEffect(TypedDict):
    type: Literal["dice-gated"]
    dice: str
    threshold: int | Literal["leadership", "toughness", "save"]
    comparison: NotRequired[Literal["gte", "lte", "gt", "lt", "eq"]]
    on_success: NotRequired[EffectNode | None]
    on_fail: NotRequired[EffectNode | None]
    test: NotRequired[Test]
    roll_var: NotRequired[str]


class Outcome(TypedDict):
    results: list[Result]
    effect: EffectNode


class DiceTableEffect(TypedDict):
    type: Literal["dice-table"]
    dice: Literal["D3", "D6"]
    outcomes: list[Outcome]


class ConditionalEffect(TypedDict):
    type: Literal["conditional"]
    condition: Condition
    effect: EffectNode


class Option(TypedDict):
    name: str
    requirement: DiceRequirementSpec
    effect: EffectNode


class DicePoolAllocationEffect(TypedDict):
    type: Literal["dice-pool-allocation"]
    pool: Pool
    max_activations: int
    options: list[Option]


class Selector(TypedDict):
    count: int
    max_count: NotRequired[int]
    keywords: NotRequired[list[str]]
    owner: Literal["friendly", "enemy"]
    target_kind: NotRequired[Literal["unit", "model"]]
    within_inches: NotRequired[float]
    eligibility: NotRequired[Condition]
    min_count: NotRequired[int]
    range_inches: NotRequired[float]
    visibility_required: NotRequired[bool]
    engagement_relation: NotRequired[
        Literal["any", "engaged-with-bearer", "not-engaged-with-bearer"]
    ]
    reference: NotRequired[Literal["bearer", "bearer-unit"]]
    within_inches_from: NotRequired[SelectionReference]
    visible_to: NotRequired[SelectionReference]
    selection_limit: NotRequired[SelectionLimit]
    model_names: NotRequired[list[ModelName]]
    excluded_keywords: NotRequired[list[ExcludedKeyword]]
    bind_as: NotRequired[str]


class Selector1(TypedDict):
    count: NotRequired[int]
    max_count: int
    keywords: NotRequired[list[str]]
    owner: Literal["friendly", "enemy"]
    target_kind: NotRequired[Literal["unit", "model"]]
    within_inches: NotRequired[float]
    eligibility: NotRequired[Condition]
    min_count: NotRequired[int]
    range_inches: NotRequired[float]
    visibility_required: NotRequired[bool]
    engagement_relation: NotRequired[
        Literal["any", "engaged-with-bearer", "not-engaged-with-bearer"]
    ]
    reference: NotRequired[Literal["bearer", "bearer-unit"]]
    within_inches_from: NotRequired[SelectionReference]
    visible_to: NotRequired[SelectionReference]
    selection_limit: NotRequired[SelectionLimit]
    model_names: NotRequired[list[ModelName]]
    excluded_keywords: NotRequired[list[ExcludedKeyword]]
    bind_as: NotRequired[str]


class SelectUnitsEffect(TypedDict):
    type: Literal["select-units"]
    selector: Selector | Selector1
    effect: EffectNode


class Selector2(TypedDict):
    owner: Literal["friendly", "enemy"]
    keywords: NotRequired[list[Keyword2]]
    target_kind: NotRequired[Literal["unit", "model"]]
    within_inches: NotRequired[float]
    engagement_relation: NotRequired[Literal["engaged-with-bearer", "not-engaged-with-bearer"]]
    reference: NotRequired[Literal["bearer", "bearer-unit"]]
    member_of: NotRequired[Literal["bearer-unit"]]
    model_names: NotRequired[list[ModelName]]
    excluded_keywords: NotRequired[list[ExcludedKeyword]]
    bind_as: NotRequired[str]
    eligibility: NotRequired[Condition]
    within_objective: NotRequired[SelectionReference]


class ForEachUnitEffect(TypedDict):
    type: Literal["for-each-unit"]
    selector: Selector2
    effect: EffectNode


class Modifier1(TypedDict):
    move_type: NotRequired[
        Literal[
            "normal",
            "advance",
            "pile-in",
            "consolidation",
            "reactive",
            "surge",
            "redeploy",
            "scout",
            "infiltrate",
            "shoot-and-scoot",
            "ingress",
            "take-to-the-skies",
        ]
    ]
    distance: NotRequired[int | str]
    passthrough: NotRequired[
        list[
            Literal[
                "non-titanic-models",
                "friendly-vehicles",
                "friendly-monsters",
                "terrain-le-4",
                "tall-terrain",
                "all-terrain",
            ]
        ]
    ]
    vertical_limit: NotRequired[int]
    waives_distance_penalty: NotRequired[bool]
    ignore_vertical: NotRequired[bool]
    replaces_default: NotRequired[bool]
    to_reserves: NotRequired[bool]
    applies_to_moves: NotRequired[list[Literal["normal", "advance", "fall-back", "charge"]]]
    name: NotRequired[str]
    excludes_keyword: NotRequired[str]
    max_units: NotRequired[int]
    marker: NotRequired[Marker]
    condition: NotRequired[Condition]


class MovementModifierEffect(TypedDict):
    type: Literal["movement-modifier"]
    target: Literal[
        "self",
        "bearer",
        "unit",
        "attached-unit",
        "attacker",
        "defender",
        "target",
        "friendly-within-aura",
        "enemy-within-aura",
        "all-friendly",
        "all-enemy",
    ]
    modifier: Modifier1
    after_move: NotRequired[EffectNode]


class Modifier2(TypedDict):
    range: NotRequired[int | list[RangeItem]]
    range_bonus: NotRequired[int]
    of: NotRequired[str]
    effect: NotRequired[EffectNode]
    eligible: NotRequired[Eligible]
    emitter_filter: NotRequired[KeywordFilter]
    recipient_filter: NotRequired[KeywordFilter]


class AuraEffect(TypedDict):
    type: Literal["aura"]
    target: Literal["enemy-within-aura", "friendly-within-aura"]
    modifier: Modifier2


class Select(TypedDict):
    scope: Literal["enemy-unit", "friendly-unit"]
    count: NotRequired[int]
    timing: NotRequired[str]
    within_inches: NotRequired[float]
    reference: NotRequired[Literal["bearer", "bearer-unit"]]
    visibility_required: NotRequired[bool]
    keywords: NotRequired[list[Keyword2]]
    keyword_match: NotRequired[Literal["all", "any"]]
    eligibility: NotRequired[Condition]
    visible_to: NotRequired[SelectionReference]
    excluded_keywords: NotRequired[list[ExcludedKeyword]]
    bind_as: NotRequired[str]
    within_inches_from: NotRequired[SelectionReference]
    selection_limit: NotRequired[SelectionLimit2]


class Applies(TypedDict):
    to: Literal[
        "target", "attackers-of-target", "bearer-attacks-target", "bound-unit-attacks-reference"
    ]
    effect: EffectNode
    attacker_keywords: NotRequired[list[AttackerKeyword]]
    attacker_unit_keywords: NotRequired[list[AttackerUnitKeyword]]
    beneficiary: NotRequired[EventOrSelectionReference]
    reference: NotRequired[SelectionReference]


class DesignateTargetEffect(TypedDict):
    type: Literal["designate-target"]
    designation: str
    select: Select
    applies: Applies
    duration: NotRequired[
        Literal["phase", "turn", "battle-round", "battle", "until-next-command-phase"]
    ]


class Option1(TypedDict):
    name: str
    effect: EffectNode


class StanceSelectEffect(TypedDict):
    type: Literal["stance-select"]
    mode: Literal["re-selectable", "consumable"]
    scope: NotRequired[Literal["army", "unit"]]
    select: NotRequired[str]
    options: list[Option1]


class Risk(TypedDict):
    test: str
    on_fail: EffectNode


class RiskRewardEffect(TypedDict):
    type: Literal["risk-reward"]
    reward: EffectNode
    risk: Risk


class IssueOrdersEffect(TypedDict):
    type: Literal["issue-orders"]
    count: NotRequired[int]
    range: NotRequired[float]
    eligible: NotRequired[Eligible1]
    options: list[Option1]


class Eligibility(TypedDict):
    requires_keyword: NotRequired[list[str]]
    excludes_keyword: NotRequired[list[str]]
    selector_count: NotRequired[int]
    requires: NotRequired[list[Condition]]


class Action1(TypedDict):
    id: str
    label: str
    when: ResourceActionMenuTrigger | list[ResourceActionMenuTrigger]
    cost: Cost1
    eligibility: NotRequired[Eligibility]
    usage: NotRequired[Usage]
    duration: NotRequired[Literal["immediate", "until-end-of-phase", "until-end-of-turn"]]
    effect: EffectNode


class ResourceActionMenuEffect(TypedDict):
    type: Literal["resource-action-menu"]
    menu_id: str
    pool_id: str
    shared_usage: NotRequired[SharedUsage]
    actions: list[Action1]


class ResourceActionMenuTrigger(TypedDict):
    event: GameEvent
    subject: NotRequired[
        Literal["self", "bearer", "friendly-unit", "enemy-unit", "any-unit", "model-in-bearer"]
    ]
    proximity: NotRequired[Proximity1]
    move_types: NotRequired[list[Literal["normal", "advance", "fall-back", "charge"]]]
    condition: NotRequired[Condition]
    optional: NotRequired[bool]
    cost: NotRequired[Cost2]
    window: NotRequired[str]
    binds_event_variable: NotRequired[str]


class NamedRegionBranch(TypedDict):
    source: NamedRegionBranchActor
    beneficiary: NamedRegionBranchActor
    target: Literal[
        "self",
        "bearer",
        "unit",
        "attached-unit",
        "attacker",
        "defender",
        "target",
        "friendly-within-aura",
        "enemy-within-aura",
        "all-friendly",
        "all-enemy",
    ]
    timing: NamedRegionBranchTiming
    duration: str
    effect: EffectNode
    optional: bool


class NamedRegionConsumer(TypedDict):
    state_ref: NamedRegionRef
    beneficiary_gate: BeneficiaryGate
    membership: NamedRegionMembership
    qualified_condition: Condition
    default_branch: NamedRegionBranch
    qualified_branch: NamedRegionBranch
    attack_condition: NotRequired[Condition]


class NamedRegionState(TypedDict):
    region_ref: NamedRegionRef
    producer: NamedRegionProducer
    consumer: NamedRegionConsumer
    branch_precedence: Literal["qualified-replaces-default"]


class Consumer(TypedDict):
    relation: Literal["attacks-selected-unit", "within-selected-marker"]
    beneficiary: Literal["bearer", "unit"]
    effect: EffectNode
    reference: NotRequired[SelectionReference]


class PersistentDesignationEffect(TypedDict):
    type: Literal["persistent-designation"]
    operation: NotRequired[Literal["establish", "replace"]]
    designation: str
    select: Select1
    consumer: NotRequired[Consumer]
    duration: Literal["phase", "turn", "battle-round", "battle", "until-next-command-phase"]
    lifecycle: NotRequired[Lifecycle]


class SelectObjectiveEffect(TypedDict):
    type: Literal["select-objective"]
    selector: ObjectiveSelector
    effect: EffectNode


class ForEachObjectiveEffect(TypedDict):
    type: Literal["for-each-objective"]
    selector: ObjectiveSelector
    effect: EffectNode


class PairedDesignationEffect(TypedDict):
    type: Literal["paired-designation"]
    duration: Literal["phase"]
    observer: Observer
    spotted: Spotted
    guided: Guided
    observer_eligibility: Condition
    effects: EffectNode


Effect: TypeAlias = EffectNode


class GenerationItem(TypedDict):
    condition: Condition
    amount: StatValue


class ResourcePool(TypedDict):
    id: EntityId
    name: str
    faction_id: EntityId
    pool_type: Literal["token", "dice-pool", "counter"]
    generation: NotRequired[list[GenerationItem]]
    max_size: NotRequired[int | None]
    game_version: GameVersionRef
