# Generated by codegen/gen_typeddicts.py — do not edit. CI fails on drift.

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypeAlias, TypedDict, Union


BundledSchemas: TypeAlias = Any


EntityId: TypeAlias = str


Edition: TypeAlias = str


DataslateVersion: TypeAlias = str


Keyword: TypeAlias = str


KeywordList: TypeAlias = list[Keyword]


StatValue: TypeAlias = int | str


ContributorRef: TypeAlias = str


Phase: TypeAlias = Literal["command", "movement", "shooting", "charge", "fight"]


PhaseList: TypeAlias = list[Phase]


SourceType: TypeAlias = Literal[
    "ability", "stratagem", "enhancement", "detachment-rule", "faction-rule"
]


PlayerTurn: TypeAlias = Literal["your-turn", "opponent-turn", "either"]


BattleSize: TypeAlias = Literal["incursion", "strike-force"]


ForceDispositionId: TypeAlias = Literal[
    "take-and-hold", "disruption", "purge-the-foe", "priority-assets", "reconnaissance"
]


class Vec2(TypedDict):
    x: float
    y: float


class Footprint1(TypedDict):
    type: Literal["rectangle"]
    width: float
    height: float


class Footprint2(TypedDict):
    type: Literal["right-triangle"]
    width: float
    height: float


class Footprint3(TypedDict):
    type: Literal["polygon"]
    points: list[Vec2]


Footprint: TypeAlias = Footprint1 | Footprint2 | Footprint3


TerrainAreaKeyword: TypeAlias = Literal["obscuring", "hidden", "plunging-fire"]


class BaseSize(TypedDict):
    shape: Literal["round", "oval", "flying-base", "hull", "unique"]
    diameter: NotRequired[float]
    width: NotRequired[float]
    length: NotRequired[float]
    size: NotRequired[Literal["small", "large"]]
    draft: NotRequired[bool]


class GameVersionRef(TypedDict):
    edition: Edition
    dataslate: DataslateVersion


class ZoneShape1(TypedDict):
    type: Literal["rectangle"]
    width: float
    height: float


class ZoneShape2(TypedDict):
    type: Literal["polygon"]
    points: list[Vec2]


ZoneShape: TypeAlias = ZoneShape1 | ZoneShape2


Side: TypeAlias = Literal["attacker", "defender"]


class Zone(TypedDict):
    player: Side
    name: NotRequired[str]
    shape: ZoneShape
    position: Vec2
    color: NotRequired[str]


class Territory(TypedDict):
    player: Side
    shape: ZoneShape
    position: Vec2


class DeploymentPattern(TypedDict):
    id: EntityId
    name: str
    source: NotRequired[str]
    description: NotRequired[str]
    zones: list[Zone]
    territories: NotRequired[list[Territory]]
    objectives: NotRequired[list[Vec2]]
    recommended_terrain_layout_ids: NotRequired[list[EntityId]]
    game_version: GameVersionRef


class Restrictions(TypedDict):
    required_keywords: NotRequired[KeywordList]
    excluded_keywords: NotRequired[KeywordList]
    notes: NotRequired[str]


class Detachment(TypedDict):
    id: EntityId
    name: str
    faction_id: EntityId
    detachment_rule_id: NotRequired[EntityId | None]
    detachment_points: NotRequired[int | None]
    force_dispositions: NotRequired[list[EntityId]]
    enhancement_ids: NotRequired[list[EntityId]]
    stratagem_ids: NotRequired[list[EntityId]]
    restrictions: NotRequired[Restrictions | None]
    game_version: GameVersionRef


class Enhancement(TypedDict):
    id: EntityId
    name: str
    detachment_id: EntityId
    cost: int
    points_provisional: NotRequired[bool]
    upgrade_tag: NotRequired[bool]
    max_targets: NotRequired[int]
    keyword_restrictions: NotRequired[KeywordList]
    exclusion_keywords: NotRequired[KeywordList | None]
    ability_id: NotRequired[EntityId | None]
    is_unique: NotRequired[bool]
    game_version: GameVersionRef


class Faction(TypedDict):
    id: EntityId
    name: str
    parent_faction_id: NotRequired[EntityId | None]
    game_version: GameVersionRef
    keywords: NotRequired[KeywordList]
    aliases: NotRequired[list[str]]
    faction_rule_id: NotRequired[EntityId | None]


class ForceDisposition(TypedDict):
    id: ForceDispositionId
    name: str
    text: NotRequired[str]
    game_version: GameVersionRef


class GameVersion(TypedDict):
    edition: Edition
    dataslate: DataslateVersion
    effective_date: str
    label: NotRequired[str]
    supersedes: NotRequired[DataslateVersion | None]


class HullShape(TypedDict):
    id: EntityId
    name: str
    points: list[Vec2]
    bounds_width_in: float
    bounds_height_in: float
    game_version: GameVersionRef


class LeaderAttachment(TypedDict):
    leader_id: EntityId
    eligible_bodyguard_ids: list[EntityId]
    game_version: GameVersionRef


class MissionMatchup(TypedDict):
    id: EntityId
    disposition: ForceDispositionId
    opponent_disposition: ForceDispositionId
    mission_id: EntityId
    game_version: GameVersionRef


class Mission(TypedDict):
    id: EntityId
    name: str
    source: NotRequired[str]
    description: NotRequired[str]
    vp_per_game_cap: NotRequired[int]
    vp_per_round_cap: NotRequired[int]
    deployment_pattern_ids: NotRequired[list[EntityId]]
    game_version: GameVersionRef


class BattleRound(TypedDict):
    min: NotRequired[int]
    max: NotRequired[int]


class ScoringTrigger(TypedDict):
    phase: NotRequired[Phase]
    timing: NotRequired[
        Literal["start-of-turn", "end-of-turn", "start-of-phase", "end-of-phase", "end-of-battle"]
    ]
    player_turn: NotRequired[PlayerTurn]
    battle_round: NotRequired[BattleRound]


class UnitFilter(TypedDict):
    model_count_min: NotRequired[int]
    model_count_max: NotRequired[int]
    wounds_min: NotRequired[int]
    keywords: NotRequired[KeywordList]


class ArmyCompositionPredicate(TypedDict):
    subject: Literal["self", "opponent"]
    quantifier: Literal["any", "none"]
    unit_filter: UnitFilter


class WhenDrawn(TypedDict):
    operation: Literal["reshuffle", "replace", "redraw", "draw-extra", "swap"]
    card_ids: NotRequired[list[EntityId]]
    condition: NotRequired[ArmyCompositionPredicate]
    battle_round: NotRequired[BattleRound]


class TargetRestrictions(TypedDict):
    required_keywords: NotRequired[KeywordList]
    excluded_keywords: NotRequired[KeywordList]
    notes: NotRequired[str]


class Stratagem(TypedDict):
    id: EntityId
    name: str
    category: Literal["core", "detachment"]
    type: NotRequired[Literal["battle-tactic", "strategic-ploy", "epic-deed", "wargear"]]
    detachment_id: NotRequired[EntityId | None]
    cp_cost: int
    phases: PhaseList
    player_turn: PlayerTurn
    timing: Literal["once-per-phase", "once-per-turn", "once-per-battle", "unlimited"]
    target_restrictions: NotRequired[TargetRestrictions | None]
    ability_id: NotRequired[EntityId | None]
    game_version: GameVersionRef


class TargetProfile(TypedDict):
    id: EntityId
    name: str
    description: NotRequired[str]
    faction_id: EntityId
    unit_id: EntityId
    model_count_override: NotRequired[int | None]
    game_version: GameVersionRef


class Objective(TypedDict):
    position: NotRequired[Vec2]
    control_range_inches: NotRequired[float]


class Ref(TypedDict):
    kind: Literal["vertex"]
    index: int


class Ref1(TypedDict):
    kind: Literal["face"]
    side: Literal["min-x", "max-x", "min-y", "max-y"]


class Keystone(TypedDict):
    edge: Literal["left", "right", "top", "bottom"]
    ref: Ref | Ref1


class Piece(TypedDict):
    id: NotRequired[EntityId]
    name: NotRequired[str]
    piece_type: NotRequired[Literal["area", "feature"]]
    template: NotRequired[EntityId]
    footprint: NotRequired[Footprint]
    position: Vec2
    rotation_degrees: NotRequired[float]
    mirror: NotRequired[Literal["none", "horizontal", "vertical"]]
    parent_area_id: NotRequired[EntityId]
    floor: NotRequired[int]
    height_inches: NotRequired[float]
    terrain_area_keywords: NotRequired[list[TerrainAreaKeyword]]
    link_group: NotRequired[str]
    objective_role: NotRequired[Literal["home", "expansion", "center"]]
    is_objective: NotRequired[bool]
    objective: NotRequired[Objective]
    keystones: NotRequired[list[Keystone]]


class TerrainLayout(TypedDict):
    id: EntityId
    name: str
    source: NotRequired[str]
    description: NotRequired[str]
    mission_matchup_id: NotRequired[EntityId]
    variant: NotRequired[int]
    deployment_pattern_id: NotRequired[EntityId]
    pieces: NotRequired[list[Piece]]
    game_version: GameVersionRef


class ComposedFeature(TypedDict):
    id: NotRequired[EntityId]
    template: EntityId
    position: Vec2
    rotation_degrees: NotRequired[float]
    mirror: NotRequired[Literal["none", "horizontal", "vertical"]]
    floor: NotRequired[int]


class UpperFloor(TypedDict):
    footprint: Footprint
    floor: NotRequired[int]


class TerrainTemplate(TypedDict):
    id: EntityId
    name: str
    kind: Literal["area", "feature"]
    source: NotRequired[str]
    footprint: Footprint
    default_height_inches: NotRequired[float]
    default_blocking: NotRequired[bool]
    ground_accessible: NotRequired[bool]
    upper_floor: NotRequired[UpperFloor]
    default_terrain_area_keywords: NotRequired[list[TerrainAreaKeyword]]
    features: NotRequired[list[ComposedFeature]]
    game_version: GameVersionRef


class Model(TypedDict):
    name: str
    profile_name: NotRequired[str | None]
    min: int
    max: int
    default_weapon_ids: NotRequired[list[EntityId]]
    is_leader_model: NotRequired[bool]
    base_size_mm: NotRequired[BaseSize]
    hull_shape_id: NotRequired[EntityId | None]


class UnitComposition(TypedDict):
    unit_id: EntityId
    models: list[Model]
    game_version: GameVersionRef


class Profile(TypedDict):
    name: NotRequired[str]
    M: StatValue
    T: int
    W: int
    Sv: int
    invuln_sv: NotRequired[int | None]
    Ld: int
    OC: int


class Point(TypedDict):
    models: int
    cost: int


class ModelCount(TypedDict):
    min: int
    max: int


class TransportCapacity(TypedDict):
    capacity: int
    keyword_restrictions: NotRequired[KeywordList | None]
    exclusion_keywords: NotRequired[KeywordList | None]


class Unit(TypedDict):
    id: EntityId
    name: str
    faction_id: EntityId
    role: NotRequired[
        Literal[
            "character", "battleline", "dedicated-transport", "fortification", "allied", "epic-hero"
        ]
    ]
    attachment_role: NotRequired[Literal["leader", "support"] | None]
    profiles: list[Profile]
    points: NotRequired[list[Point]]
    points_provisional: NotRequired[bool]
    keywords: NotRequired[KeywordList]
    faction_keywords: NotRequired[KeywordList]
    base_size_mm: NotRequired[BaseSize | None]
    model_count: NotRequired[ModelCount]
    weapon_ids: NotRequired[list[EntityId]]
    ability_ids: NotRequired[list[EntityId]]
    transport_capacity: NotRequired[TransportCapacity | None]
    game_version: GameVersionRef
    is_legend: NotRequired[bool]


class ModelConstraint(TypedDict):
    model_name: NotRequired[str]
    per_n_models: NotRequired[int]
    max_count: NotRequired[int]
    any_number: NotRequired[bool]


ReplacementChoiceItem: TypeAlias = list[EntityId]


class WargearOption(TypedDict):
    id: EntityId
    unit_id: EntityId
    model_constraint: NotRequired[ModelConstraint | None]
    replaces: NotRequired[list[EntityId]]
    replacement: NotRequired[list[EntityId]]
    replacement_choice: NotRequired[list[ReplacementChoiceItem]]
    is_free: NotRequired[bool]
    additional_cost: NotRequired[int | None]
    game_version: GameVersionRef


class Wargear(TypedDict):
    id: EntityId
    name: str
    category: NotRequired[str | None]
    game_version: GameVersionRef


class Stats(TypedDict):
    A: StatValue
    BS: NotRequired[int | None]
    WS: NotRequired[int | None]
    S: StatValue
    AP: int
    D: StatValue


class Parameters(TypedDict):
    value: NotRequired[StatValue]
    target_keyword: NotRequired[str]
    threshold: NotRequired[int]


class Keyword1(TypedDict):
    keyword_id: EntityId
    parameters: NotRequired[Parameters]


class Profile1(TypedDict):
    name: str
    range: NotRequired[int | Literal["Melee"]]
    stats: Stats
    keywords: NotRequired[list[Keyword1]]


class Weapon(TypedDict):
    id: EntityId
    name: str
    type: Literal["ranged", "melee"]
    profiles: list[Profile1]
    game_version: GameVersionRef


class AppliesTo(TypedDict):
    required_keywords: NotRequired[KeywordList]
    excluded_keywords: NotRequired[KeywordList]


class Interaction(TypedDict):
    ability_ref: EntityId
    type: Literal["conflicts-with", "combos-with", "superseded-by", "requires", "replaces"]
    notes: NotRequired[str]


class SimpleCondition(TypedDict):
    type: Literal[
        "phase-is",
        "timing-is",
        "player-turn-is",
        "unit-below-starting-strength",
        "unit-below-half-strength",
        "unit-has-keyword",
        "unit-within-range-of",
        "model-is-leader",
        "target-has-keyword",
        "charged-this-turn",
        "advanced-this-turn",
        "remained-stationary",
        "is-battle-shocked",
        "has-lost-wounds",
        "was-hit-by-attack",
        "opponent-unit-within-range",
        "within-range-of-objective",
        "attack-is-type",
        "has-fought-this-phase",
        "destroyed-by-attack-type",
        "controls-objective",
        "is-attached",
        "terrain-area-control",
        "engagement-state",
        "territory-control",
        "fights-first",
        "disposition-matches",
        "units-destroyed",
        "units-destroyed-comparison",
        "objective-majority",
        "action-completed",
        "objective-has-tag",
        "unit-has-tag",
        "terrain-has-tag",
        "new-objective-controlled",
        "engagement-fronts",
        "destroyed-while-on-objective",
        "destroyed-in-tagged-terrain",
        "operation-markers",
    ]
    parameters: NotRequired[dict[str, Any]]
    negated: NotRequired[bool]


class SingleEffect(TypedDict):
    type: Literal[
        "stat-modifier",
        "roll-modifier",
        "re-roll",
        "mortal-wounds",
        "feel-no-pain",
        "invulnerable-save",
        "ward",
        "keyword-grant",
        "movement-modifier",
        "deep-strike",
        "fallback-and-act",
        "fight-first",
        "fight-last",
        "shoot-on-death",
        "fight-on-death",
        "objective-control-modifier",
        "leadership-modifier",
        "damage-reduction",
        "attack-restriction",
        "ability-grant",
        "cp-gain",
        "cp-refund",
        "model-destruction",
        "resurrection",
        "resource-gain",
        "resource-spend",
        "charge-roll-modifier",
        "terrain-area-tag",
        "objective-tag",
        "unit-tag",
        "bs-modifier",
        "engagement-passthrough",
    ]
    target: Literal[
        "self",
        "bearer",
        "unit",
        "attached-unit",
        "attacker",
        "defender",
        "friendly-within-aura",
        "enemy-within-aura",
        "all-friendly",
        "all-enemy",
    ]
    modifier: NotRequired[dict[str, Any]]


class Pool(TypedDict):
    count: int
    die: str


class Requirement(TypedDict):
    type: Literal["pair", "triple", "single", "run"]
    min_value: int


class Scope(TypedDict):
    range: Literal[
        "self",
        "unit",
        "attached",
        "aura-6",
        "aura-9",
        "aura-12",
        "aura-custom",
        "engagement-range",
        "any-visible",
        "any-on-battlefield",
        "terrain-within-range",
    ]
    duration: Literal[
        "phase",
        "turn",
        "battle-round",
        "battle",
        "until-next-command-phase",
        "one-use",
        "permanent",
    ]
    range_inches: NotRequired[float]


class InteractionFlag(TypedDict):
    ability_a: EntityId
    ability_b: EntityId
    interaction_type: Literal[
        "conflicts", "combos", "sequencing-dependent", "stacks", "does-not-stack", "replaces"
    ]
    resolution: NotRequired[str]
    faq_reference: NotRequired[str]
    disputed: NotRequired[bool]
    game_version: GameVersionRef
    authored_by: NotRequired[ContributorRef]


class PhaseMapping(TypedDict):
    source_id: EntityId
    source_type: SourceType
    phases: PhaseList
    game_version: GameVersionRef
    authored_by: NotRequired[ContributorRef]


class TimingFlag(TypedDict):
    source_id: EntityId
    source_type: SourceType
    timing: Literal[
        "start-of-phase",
        "end-of-phase",
        "before-hit-roll",
        "after-hit-roll",
        "before-wound-roll",
        "after-wound-roll",
        "before-save-roll",
        "after-save-roll",
        "before-damage-roll",
        "after-damage-roll",
        "before-charge-roll",
        "after-charge-roll",
        "before-advance-roll",
        "after-advance-roll",
        "before-battle-shock",
        "after-battle-shock",
        "on-unit-selected",
        "on-unit-destroyed",
        "on-model-destroyed",
        "on-damage-allocated",
    ]
    game_version: GameVersionRef
    authored_by: NotRequired[ContributorRef]


class Action(TypedDict):
    action_id: NotRequired[str]
    starts: NotRequired[Phase]
    timing: NotRequired[Literal["start-of-battle", "start-of-turn", "end-of-turn"]]
    battle_round: NotRequired[BattleRound]
    player_turn: NotRequired[PlayerTurn]
    units: NotRequired[Condition]
    use_limit: NotRequired[int]
    use_limit_scope: NotRequired[Literal["per-turn", "per-game"]]
    completes: NotRequired[Condition]
    effect: NotRequired[Effect]
    restrictions: NotRequired[Condition]


class Awards(TypedDict):
    trigger: ScoringTrigger
    when: NotRequired[Condition]
    vp: int
    vp_per: NotRequired[int]
    per: NotRequired[str]
    per_max: NotRequired[int]
    vp_max: NotRequired[int]
    mode: NotRequired[Literal["fixed", "tactical"]]
    cumulative: NotRequired[bool]
    exclusive_group: NotRequired[str]


class Awards1(TypedDict):
    trigger: ScoringTrigger
    when: NotRequired[Condition]
    vp: NotRequired[int]
    vp_per: int
    per: str
    per_max: NotRequired[int]
    vp_max: NotRequired[int]
    mode: NotRequired[Literal["fixed", "tactical"]]
    cumulative: NotRequired[bool]
    exclusive_group: NotRequired[str]


class SecondaryCard(TypedDict):
    id: EntityId
    name: str
    card_type: NotRequired[Literal["secondary", "primary"]]
    subtype: NotRequired[str]
    when_drawn: NotRequired[WhenDrawn]
    actions: NotRequired[list[Action]]
    awards: NotRequired[list[Awards | Awards1]]
    text: NotRequired[str]
    game_version: GameVersionRef


class WeaponKeyword(TypedDict):
    id: EntityId
    name: str
    required_parameters: list[Literal["value", "target_keyword", "threshold"]]
    effect: Effect | None
    game_version: GameVersionRef


class Ability(TypedDict):
    ability_id: EntityId
    name: str
    authored_by: ContributorRef
    game_version: GameVersionRef
    version: NotRequired[DataslateVersion]
    supersedes: NotRequired[DataslateVersion | None]
    unit_ids: NotRequired[list[EntityId]]
    faction_id: NotRequired[EntityId | None]
    detachment_id: NotRequired[EntityId | None]
    ability_type: NotRequired[
        Literal["core", "faction", "detachment", "unit", "enhancement", "stratagem"]
    ]
    behavior: NotRequired[Literal["passive", "activated", "reactive", "aura"]]
    effect: Effect
    scope: Scope
    applies_to: NotRequired[AppliesTo | None]
    interactions: NotRequired[list[Interaction]]
    disputed: NotRequired[bool]
    dispute_notes: NotRequired[str]
    community_notes: NotRequired[str]


ConditionNode: TypeAlias = Union[SimpleCondition, "CompoundCondition"]


class CompoundCondition(TypedDict):
    operator: Literal["and", "or", "not"]
    operands: list[ConditionNode]


Condition: TypeAlias = ConditionNode


EffectNode: TypeAlias = Union[
    SingleEffect,
    "ChoiceEffect",
    "SequenceEffect",
    "DiceGatedEffect",
    "ConditionalEffect",
    "DicePoolAllocationEffect",
]


class ChoiceEffect(TypedDict):
    type: Literal["choice"]
    options: list[EffectNode]
    choice_label: NotRequired[str]


class SequenceEffect(TypedDict):
    type: Literal["sequence"]
    steps: list[EffectNode]


class DiceGatedEffect(TypedDict):
    type: Literal["dice-gated"]
    dice: str
    threshold: int | Literal["leadership", "toughness", "save"]
    comparison: NotRequired[Literal["gte", "lte", "gt", "lt", "eq"]]
    on_success: NotRequired[EffectNode | None]
    on_fail: NotRequired[EffectNode | None]


class ConditionalEffect(TypedDict):
    type: Literal["conditional"]
    condition: Condition
    effect: EffectNode


class Option(TypedDict):
    name: str
    requirement: Requirement
    effect: EffectNode


class DicePoolAllocationEffect(TypedDict):
    type: Literal["dice-pool-allocation"]
    pool: Pool
    max_activations: int
    options: list[Option]


Effect: TypeAlias = EffectNode


class GenerationItem(TypedDict):
    condition: Condition
    amount: StatValue


class ResourcePool(TypedDict):
    id: EntityId
    name: str
    faction_id: EntityId
    pool_type: Literal["token", "dice-pool", "counter"]
    generation: NotRequired[list[GenerationItem]]
    max_size: NotRequired[int | None]
    game_version: GameVersionRef
