#!/usr/bin/env bash
# Regenerate the Go module's embedded assets from the canonical sources.
# Mirrors python/codegen/sync_bundle.py + sync_spec.py. CI drift-checks the
# results (git diff --exit-code), so run this after any data/schema/spec change.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

# The embedded dataset is a byte-for-byte copy of the Rust crate's bundle (the
# shared bundler all impls inherit), regenerated by `cargo run -p xtask -- bundle-data`.
cp "$ROOT/crates/wh40kdc/src/data/bundle.generated.json" "$ROOT/go/bundle.json"

# The share-token id registry (same committed copy the Python package embeds).
cp "$ROOT/python/src/wh40kdc/_share_registry.json" "$ROOT/go/share_registry.json"

# The canonical JSON Schema tree (for the validator).
rm -rf "$ROOT/go/schemas"
cp -r "$ROOT/schemas" "$ROOT/go/schemas"

# spec.go mirrors conformance/SPEC_VERSION.
SPEC="$(cat "$ROOT/conformance/SPEC_VERSION" | tr -d '[:space:]')"
cat > "$ROOT/go/spec.go" <<EOF
// Code generated by codegen/sync.sh — DO NOT EDIT.
// Mirrors conformance/SPEC_VERSION; CI fails on drift.

package wh40kdc

// SpecVersion is the conformance corpus spec version this implementation was
// tested against. The runner refuses to participate in a cross-impl run if the
// differ's spec version doesn't match.
const SpecVersion = $SPEC
EOF

echo "go: synced bundle.json, share_registry.json, schemas/, spec.go (SPEC_VERSION=$SPEC)"
