// Code generated by codegen/sync.sh — DO NOT EDIT.
// Mirrors conformance/SPEC_VERSION; CI fails on drift.

package wh40kdc

// SpecVersion is the conformance corpus spec version this implementation was
// tested against. The runner refuses to participate in a cross-impl run if the
// differ's spec version doesn't match.
const SpecVersion = 34
